### ISSUE TITLE
Authentication: implement a means for automatic testing against deployment

### ISSUE THREAD

**Issue by bmccandless** [chanzuckerberg/single-cell#103]
There is currently not a way to programmatically authenticate to portal or explorer, for use in end to end tests.
Authentication is a manual process.

This task involves investigating best practices, and consulting with teams that have implemented this, such as IDSeq or Meta. 

Definition of Done:
[ ] a mechanism to programmatically authenticate to portal is implemented
[ ] a mechanism to programmatically authenticate to explorer is implemented
[ ] a least one test case using this is written for both apps to verify it works, and keeps working.

**Comment by brianraymor** [comment]
Closed per conversation with @maniarathi
