### ISSUE TITLE
Example of Configuration.yaml in Corpora Schema guide is outdated

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#112]
This was reported by @jahilton. 

The [schema](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/backend/schema/corpora_schema.md) version is 1.1.0, but the sample [configuration.yaml](https://github.com/chanzuckerberg/cellxgene/blob/main/dev_docs/schema_guide.md#configuration-yaml) in the Corpora Schema Guide has not been updated to reflect the changes, including some [deprecations of fields]( https://github.com/chanzuckerberg/single-cell/issues/75).

**Comment by mckinsel** [comment]
We're moving this to the single-cell-curation repo (which will be public shortly), and the guide has been updated.

**Comment by brianraymor** [comment]
You can use `Transfer issue` to accomplish that task.

<img width="184" alt="Screen Shot 2021-02-16 at 1 48 59 PM" src="https://user-images.githubusercontent.com/3644743/108125774-cdaf0180-705d-11eb-8943-a9a879d127b0.png">

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell-curation #17](https://github.com/chanzuckerberg/single-cell-curation/issues/17) via [**ZenHub**](https://www.zenhub.com/)
