### ISSUE TITLE
Curators can add gene sets to a dataset in a private collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#115]
**Story**

_A curator can add gene sets to a dataset in a private collection._

---

**Model**

See [Link by adding a gene set “set” to a dataset](https://docs.google.com/document/d/15rQuHfjezUo0RcJ3xVoRuWLP6OQ9bqiGDanmczehJtE/edit#heading=h.h1v05pg02lhb) in the _thought experiments_ document. 

The curator must create a gene set file that is specific to a dataset in the private collection. 

---

**Requirements**

_Adding Gene Set(s) to a dataset in a private collection_

- MUST support the ability for the curator to select and upload a file containing one or more gene sets from their local drive

---

_Validating Gene Set files during upload_

The validation requirements for the file format are defined in the [**Gene Set File Format**](https://github.com/chanzuckerberg/single-cell-curation/blob/main/docs/gene_sets.md).

---

_Verifying that gene sets are assigned to a dataset_

There MUST be a simple UX _hint_ that allows the curator to quickly verify either the number of gene sets or the names of the gene sets that are assigned to a dataset. See Gene Sets Tag in the **UX Design** section. These hints MUST NOT be displayed in public collections to consumers, only to curators in private collections including revisions. 

---

**UX Design **

[Add Gene Sets](https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=178%3A1414)
[Upload Gene Set](https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=230%3A0)
[Gene Sets Tag](https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=623%3A64)

**Comment by hthomas-czi** [comment]
@brianraymor I favor the Keep Both/Stop/Replace pattern that users ought to be familiar with.

**Comment by brianraymor** [comment]
I will _make it so_.

**Comment by tihuan** [comment]
Hi @brianraymor ! @MDunitz and I just sync'd on that BE will only store the values from the first 4 fields, and all the optional fields will be ignored. 

So I just want to make sure that the statement here:

> The gene set file may contain additional columns that the publisher wants to share with consumers but will not be represented in the UI.

means that DP will not show the optional fields in the UI NOR provide the optional fields in the downloaded genesets, right?

Thank you!

**Comment by brianraymor** [comment]
> means that DP will not show the optional fields in the UI NOR provide the optional fields in the downloaded genesets, right?

No. The optional fields must be included in downloads; otherwise, they're not shared with the consumer.

**Comment by tihuan** [comment]
Ah got it! Thank you 🙆‍♂️ I'll sync with @MDunitz again!

**Comment by tihuan** [comment]
Done! We'll preserve the optional fields!

@brianraymor how about comments 😱 ??

**Comment by brianraymor** [comment]
Validation should simply ignore comments. 

Based on our related conversation with Bruce about its use, I intend to propose the elimination of the comment requirement in both portal and desktop when Signe returns. There is no way that the portal can persist and then reproduce comments in downloads unless a comment was embedded between gene symbols rows for a particular gene set:

`gene set A` row
`#comment`
`gene set B` row

would the comment belong to gene set A or B?

**Comment by tihuan** [comment]
hmm yeah lol Great point!

**Comment by tihuan** [comment]
@brianraymor for `Duplicate Gene Set Name`, I think we can only check if any of the genet set names in the CSV file collide with an existing gene set name in the collection, but we can't check duplicate gene set names within the CSV file, because genes belonging to the same gene set will have the same gene set name in the first column, I believe? 

So we can cross out requirement `Duplicate Gene Set Name` and just keep `New Gene Set Name duplicates an existing Gene Set Name in the private collection`?

E.g.,

`macrophage` is not duplicate gene set name

![Screen Shot 2021-03-03 at 4.35.48 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/2c187272-b649-4134-a784-53743869de08)

Thank you!

**Comment by brianraymor** [comment]
The Duplicate gene set name looks like this pattern:


**gene_set_name**
club.cell
club.cell
club.cell
macrophage
macrophage
**club.cell**

**Comment by tihuan** [comment]
Ah I see! Is this a commonly known rule for scientists that entry order matters, or do people usually assume entry order doesn't matter as long as they have the right `gene_set_name`?

**Comment by brianraymor** [comment]
Bruce and I have different perspective on this. I don't want to guess user intentions. For example, they may have cut-and-paste a row and forgot to change a name. I prefer to start strict and loosen restrictions based on curator feedback.

**Comment by tihuan** [comment]
Got it that sounds good! What error message should we show the user when this happens?

I'm thinking about:

>Gene set name: '${gene_set_name}' already exists in the previous section of the CSV. Please group genes that belong to the same gene set in the same section

Not sure if that's clear enough?

Thanks!

CC: @hthomas-czi

**Comment by hthomas-czi** [comment]
> ${gene_set_name} was already used in this file. Please group all genes in a gene set together.

**Comment by tihuan** [comment]
That looks much better lol Thanks a lot, @hthomas-czi ! @brianraymor what do you think?

**Comment by brianraymor** [comment]
LGTM.

**Comment by tihuan** [comment]
Awesome thanks all!

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
