### ISSUE TITLE
Curators can publish a private collection containing gene sets

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#119]
**Story**

_Curators can publish a private collection containing gene sets for download or exploration in cellxgene explorer._

---
_Updates to [Publish Private Collection](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/29)_

`Publish` must be unavailable in a **private** collection under the following conditions:
- A gene set is being processed (upload, validation).
- ~~A gene set has a pending error condition such as a conversion failure.~~

**Comment by hthomas-czi** [comment]
@brianraymor I was thinking we could have a [tag showing unassigned gene sets](https://www.figma.com/file/TKV4sJ00zWobEFkaNgklC3/Gene-Sets?node-id=178%3A1887) Thoughts?

**Comment by brianraymor** [comment]
I like the tag in general for the gene set view. I wonder whether the text should be "Not assigned to dataset" for clarity, but I defer to you, Harley.

The original question was whether we should warn the curator on `publish `in addition to providing a visual hint - not that I'm fan of "Are you sure?" prompts. 

@tihuan - second opinion for FE?

**Comment by tihuan** [comment]
Yeah I think given that editing a published collection is not easy right now, having a warning / "are you sure" prompt for the publish button when a geneset is unassigned sounds good as an easy insurance 👌 

Or could we also disable the publish button when a geneset is not linked to a dataset?

**Comment by brianraymor** [comment]
Closing. Per the 2022 Q1 plan, the design would _embed_ gene sets in datasets.
