### ISSUE TITLE
Complete security checklist prior to Portal launch

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/single-cell#120]
TrustXFN has given us a [security checklist](https://docs.google.com/document/d/1wX7z_38yfbyMzDF6URupkpb27uuvmzYeOxZB83Kl5ko/edit) to go through prior to the launch of Portal at the end of Q2. This epic will track the issues to accomplish that as well as track any issues that crop up once we go through the Trail of Bits assessment.

**Comment by brianraymor** [comment]
All child issues are complete, @maniarathi. Closing.
