### ISSUE TITLE
Verify that the cellxgene April 2020 test recommendations have been completed

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/single-cell#121]
The April 2020 pentest recommendations for cellxgene were:

- Disable HTTP Trace method
- Disable all unencrypted connections (force TLS)
- Ensure user-facing error messages are non-descript to avoid leaking memory addresses, file paths, or module/software version information

Verify with Bruce that these were actually completed.

**Comment by brianraymor** [comment]
@maniarathi - see:

- [Disable HTTP Trace method](https://github.com/chanzuckerberg/cellxgene/issues/1266)
- [Disable all unencrypted connections (force TLS)](https://github.com/chanzuckerberg/cellxgene/issues/1267)
- [Ensure user-facing error messages are non-descript to avoid leaking memory addresses, file paths, or module/software version information](https://github.com/chanzuckerberg/cellxgene/pull/1269)
