### ISSUE TITLE
Consumers need a more intuitive experience in the Collection Dataset view

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#124]
With the introduction of Collections with long lists of datasets such as [Molecular characterization of selectively vulnerable neurons in Alzheimer's Disease](https://cellxgene.cziscience.com/collections/180bff9c-c8a5-4539-b13b-ddbc00d643e6), it's not intuitive for consumers to discover `Download` without scrolling. This was also reported by @pablo-gar as one of his first experiences with the portal.

In addition, `Explore` can be successfully clicked without first selecting a dataset which is inconsistent with `Download`. 

@hthomas-czi, @tihuan, and I met and review a **small set of incremental changes** that we agreed to incorporate before implementing the Gene Sets view. 

---

Per the March 15 conversation on [**ux**](https://chanzuckerbergteam.slack.com/archives/C01CM0MG9HB/p1615843298006300?thread_ts=1615601055.006200&cid=C01CM0MG9HB), the following required fields and links MUST be displayed in the following order in the Collection-Dataset View:

1. `Contact`
2. `DOI`
3.  `Data Source` (back link to referring portal such as BICCN)
4. `Raw Data`
5. `Protocol`
6. `Lab Website`
7. `Other`

In the case of multiple links of the same type such as `DOI`, new links are appended. 

If there is `DOI` link 1 and `DOI` link 2 is added:

`Contact`
`DOI` link 1
`DOI` link 2
`Data Source`
...

Updates to `DOI` link 1 do not change its order.

---

**UX Design**

[Updated Collection Dataset view](https://www.figma.com/file/yw3j0OQADELXB3RBUIWvsX/UI-Refinement?node-id=68%3A175)

![Screen Shot 2021-03-03 at 5.24.26 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/17039e40-8488-4df1-9397-55ae760f60cb)

DoD:

1. A user will be able to explore a dataset by clicking on the cellxgene logo on its row (please show tooltip "Explore" too!)

1. A user will be able to download a dataset by clicking on the cloud download icon, which triggers the current download modal (please show tooltip "Download" too!)

1. A user will be able to add a new dataset by clicking on the newly positioned "Add" button next to the "Publish" button, which gives me options to either add a dataset or gene set

1. A user will be able to delete a dataset by using the new `...` element in the row, which shows the delete option in the dropdown

1. A user will be able to delete the collection by using the new `...` element next to the "Publish" button, which shows the delete option in the dropdown

1. A user will no longer see the radio button in each row, and the bottom Download and Delete buttons are gone too!

1. Please make sure the collection links are **sorted in the order described above** by @brianraymor in both create/edit collection form and collection view

1. **IMPORTANT** Please re-check all the access control stuff as described in [ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/987), such as non-owner should NOT be able to see and perform non-read (create, delete, update, etc.) actions to a dataset or collection they don't own. Please check with Timmy if this is unclear! Thank you!

**Comment by brianraymor** [comment]
@tihuan - can you confirm that the Collection view is already ordered as:

1. `Contact`
2. `DOI`

It looks like it is, but _measure twice cut once_:

![Screen Shot 2021-03-15 at 5.30.45 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/4d1e07d8-c048-4971-b72f-83171a64958b)

**Comment by brianraymor** [comment]
@tihuan - you may also want to update your DoD based on the additional requirements related to Links that I added to the top-level summary comment.

**Comment by tihuan** [comment]
@brianraymor 

I can confirm that collection row on the homepage is contact name first, then DOI 🙆‍♂️ 

<img width="618" alt="Screen Shot 2021-03-17 at 11 48 34 AM" src="https://user-images.githubusercontent.com/6309723/111521835-d35c3d80-8716-11eb-82fc-a209f7c83d82.png">

Will update DoD too! Thank you!

**Comment by maniarathi** [comment]
Has been pushed to prod so closing.
