### ISSUE TITLE
March 19 CZIF Policy Updates

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#126]
**This must be deployed by March 19  for portal and explorer**:

---

- [ ] Add “(updates coming)” next to Terms of Service and Privacy Policy links on **both** portal and explorer cookie banners:

> By using this site, you are agreeing to our [terms of service](https://cellxgene.cziscience.com/tos/) (updates coming). We use cookies to help us improve our future efforts, and we also use necessary cookies to make our site work. To learn more, read our [privacy policy](https://cellxgene.cziscience.com/privacy/) (updates coming).

---

- [ ] Add “(updates coming)” next to Terms of Service and Privacy Policy links at the bottom of the portal pages:

![Screen Shot 2021-03-09 at 3.42.58 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/c75416ea-dc8b-44d3-9698-a5f276015de6)

---

- [ ] Add cellxgene.cziscience.com/previewpolicies which contains:

> “Summary of April 2021 Updates to Terms of Service and Privacy Policy
> 
> We periodically update our terms and policies to ensure that they are transparent and easy to understand.
> 
> Here is a summary of the key updates from April 2021:
> 
> Cellxgene is now provided by the Chan Zuckerberg Initiative Foundation. The Chan Zuckerberg Initiative has moved its Science team to its 501(c)(3) private foundation from CZI, LLC. We’re committed to preserving the same experience for you.  
> For questions about these changes, please contact us at privacy@chanzuckerberg.com.”

**followed by the updated and merged policies which are not available until ~March 15.** 

---

- [ ] Update https://cellxgene.cziscience.com/tos/ to start with:

> We invite you to **preview** [link to cellxgene.cziscience.com/previewpolicies] our updated Terms of Use, which will go into effect on April 1, 2021.

---

- [ ] Update https://cellxgene.cziscience.com/privacy/ to start with:

> We invite you to **preview** [link to cellxgene.cziscience.com/previewpolicies] our updated Privacy Policy, which will go into effect on April 1, 2021. 

---

**Notes**:

cellxgene explorer is NOT REQUIRED to add “(updates coming)" its related menu items:

![Screen Shot 2021-03-09 at 3.39.30 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/dda0f5f3-e802-4535-b6cd-1c93401de06e)

cellxgene portal is NOT REQUIRED to update its data submission policy.

The Log In / Sign Up modal is NOT REQUIRED to add "(updates coming)" to its links since access is limited to a small set of curators.

![Screen Shot 2021-03-10 at 10.53.20 AM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/937d7389-7ef4-4da2-9f5b-96d90e2084bb)

---

**Comment by brianraymor** [comment]
@maniarathi, @tihuan, and I agreed to start this issue while waiting for the final content for the `previewpolicies` file which is due Tuesday **latest**.  An empty file can be created to allow the required linking and be populated later.

**Comment by tihuan** [comment]
@brianraymor LGTM'd!

**Comment by tihuan** [comment]
LGTM in prod!![Screen Shot 2021-03-18 at 3.44.13 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/cf08fc5c-2062-4a45-b59a-2f0626d187e8)

**Comment by tihuan** [comment]
![Screen Shot 2021-03-18 at 3.50.51 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/8b14c13b-67b8-4862-b4f1-0550f7160b35)
