### ISSUE TITLE
April 1 CZIF Policy Updates

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#130]
**This must be deployed by April 1  for portal and explorer**:

- [ ] Remove “(updates coming)” next to Terms of Service and Privacy Policy links on **both** portal and explorer cookie banners.
- [ ] Remove “(updates coming)” next to Terms of Service and Privacy Policy links at the bottom of the portal pages.
- [ ] Remove cellxgene.cziscience.com/previewpolicies.

- [ ] Replace the contents of https://cellxgene.cziscience.com/tos/ with the TOS section from [this document](https://docs.google.com/document/d/1ya_mFaYSOSaJdXHcXHYpQfwOEVokNQN6yH8zYUuohfs/edit#). 
- [ ] Replace the contents of https://cellxgene.cziscience.com/privacy/ with the Privacy section from [this document](https://docs.google.com/document/d/1ya_mFaYSOSaJdXHcXHYpQfwOEVokNQN6yH8zYUuohfs/edit#).

**Comment by maniarathi** [comment]
Verified in prod so closing.
