### ISSUE TITLE
Curators may delete a published collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#132]
**Story**

*Curators MAY delete a published collection at the request of its publisher per the agreement in the data submission policy.*

The data submission policy states:

_I understand that I have the ability to delete my data from the cellxgene portal if I later change my mind. This will not undo any prior downloads or shares of my data._

---

The `Delete Collection` UX is available in the *A Collection* view for the specific published collection. 

The collection and its contents MUST be deleted AND the permanent links for the collection and CXG(s) MUST redirect to the portal landing page and display a message to data consumers instead of returning a 404:

- For the Collection: `Collection Name` withdrawn by `Contact`.
- For each CXG: `Dataset Name` withdrawn by `Contact`.

The expectation is that the consumer has been referred to the original collection or a CXG from a reference in a publication or an external portal. 

This requirement has been nicely validated by a recent question to CZI about a deleted collection. See [**wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1634335479437800?thread_ts=1634335304.437700&cid=C024HCSH9PT).

---

**UX Design**

[Dialog](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=1227%3A5017)

[Withdrawn Collection](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=803%3A0)

**Remove** 'This action cannot be undone without manual intervention' from the `Publish Collection` _are you sure?_ confirmation.

**Comment by hthomas-czi** [comment]
@brianraymor How about this? 

"Portal users, including those linked from external sites, will be able to view and download the datasets, related metadata, and CXGs in this collection."

**Comment by brianraymor** [comment]
The MVP is complete.
