### ISSUE TITLE
Curators may add new datasets to the private revision of a public collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#137]
**A curator MAY add new datasets to the revision.**

This reuses _adding new datasets to a private collection_ with the additional requirement:

**A curator MUST easily understand the differences between the revision and the published collection.**

The added dataset MUST be labeled as `New` in the *A Collection* view.

---

**UX Design**

[Figma](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=441%3A122)

**Comment by Bento007** [comment]
Complete
