### ISSUE TITLE
Curators may delete published datasets in a private revision for a public collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#138]
**October 15 - Update ** current experience:

https://images.zenhubusercontent.com/280546849/8980095b-f495-4fc6-9f9e-c1ac46e5635b/screen_recording_2021_10_15_at_11_03_15_am.mov

**A curator MAY delete previously published datasets in the revision.**

If the revision is published, then the dataset and its CXG MUST be deleted, but the permanent link for the CXG MUST display a message to data consumers and MUST NOT return a 404:

- For each CXG: _`Dataset Name` withdrawn by `Contact`_

The expectation is that the consumer has been referred to a CXG from a reference in a publication or an external portal. 

**[[PENDING]]** - When a published dataset is deleted but not published, the `Explore` button should also preview the same  _Dataset Name` withdrawn by `Contact_ page.

**A curator MUST easily understand the differences between the revision and the published collection.**

The deleted dataset MUST be labeled as `Deleted` in the *A Collection* view.

---

**UX Design**
[Publishing with Deleted Datasets Confirmation](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=1024%3A5008)
[Withdrawn Dataset Message](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=1062%3A5177)
[Withdrawn Collection Message](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=1062%3A5185)

**Comment by hthomas-czi** [comment]
@brianraymor 

> is there a Figma with an "Are you sure?" style warning for the delete of a published dataset and an example of the "Withdrawn by Contact"?

I'm not sure if we need a confirmation for each deleted dataset. Perhaps we could show a confirmation prior to [publishing the revision](https://www.figma.com/file/jZzZF9oO0YRMxmVRDxDHp3/Public-Revisions?node-id=535%3A434). We already have a similar interaction for publishing a private collection. 

> When a published dataset is deleted but not published, the Explore button should also preview the same Dataset Name `withdrawn` byContact page.

Could you clarify what you mean by this?

**Comment by brianraymor** [comment]
@hthomas-czi 

I like your suggestion of just showing the confirmation when publishing.

Clarifying the preview experience for deleting a dataset:

1. I delete a published dataset in the revision.
2. I'm assuming that the `Explore` button is still enabled so I can "preview the deletion".  All other controls (like download) are disabled.
3. I click explore and instead of being shown a visualization. I see a message about how I withdrew this dataset.

A simpler option would be to simply disable all controls for a deleted published dataset. The curator can trust that the portal will display the appropriate message.

**Comment by hthomas-czi** [comment]
Hmmm. I need to think a little more before I can fully articulate this, but I feel like Explore and Download should retain their behavior even for deleted datasets. It seems like the user value of being able to double-check a deleted dataset is greater than the value provided by previewing the message that will appear once the revision has been published.

**Comment by brianraymor** [comment]
Download would show disabled items because the dataset is virtually deleted.

**Comment by Bento007** [comment]
Do we have an idea of what the explorer looks like for a deleted dataset?

**Comment by Bento007** [comment]
> The deleted dataset MUST be labeled as Deleted in the A Collection view.

Are all deleted datasets shown in the collection view? Even the datasets that were deleted while the dataset was private, and datasets that were deleted in previous revisions. Will these deleted datasets be visible when the collection is published?

**Comment by brianraymor** [comment]
I asked Harley for a figma - but basically, it's a page that says in a large font "Fancy Single-Cell RNAseq analysis was withdrawn by Trent".  Blinking text is optional, Harley ;-)

**Comment by brianraymor** [comment]
> Are all deleted datasets shown in the collection view? Even the datasets that were deleted while the dataset was private, and datasets that were deleted in previous revisions. Will these deleted datasets be visible when the collection is published?

No. The requirement is related to the deletion of **published** datasets. When a collection is revised and re-published, then that's the new set of published datasets.

**Comment by brianraymor** [comment]
Caching/Delay issues are addressed. Closing.
