### ISSUE TITLE
Curators want to rename datasets in a collection without uploading again

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#145]
## Context

See [original slack conversation](https://chanzuckerbergteam.slack.com/archives/C018B64J3HN/p1617654103078300?thread_ts=1617652815.070400&cid=C018B64J3HN) with @pablo-gar.

Currently, if a dataset name (`title` in [Presentation metadata](https://github.com/chanzuckerberg/single-cell-curation/blob/main/docs/corpora_schema.md#presentation-metadata)) in _A Collection_ needs to be updated for clarity, the curator must edit the dataset and then upload+replace the original in the collection. 

A pending case is [Update tabula muris brain datasets to better reflect differences ](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/40).

Updating a dataset name would currently require writing the change to the database, the dataset, and the [CXG](https://github.com/chanzuckerberg/cellxgene/blob/main/dev_docs/cxg.md#corpora-schema-encoding).

## UX Design
[Figma](https://www.figma.com/design/jEv0ZWQd0Q53aFl9nNRbBy/Portal?node-id=1250-10201&m=dev)

## Design (@nayib-jose-gloria)

Backend Estimate: 1-2 weeks x 1 engineer + 1 reviewer

- Create endpoint in both the Curation and DP APIs for patching dataset metadata such as dataset title (i.e. `PATCH /curation/v1/collections/<collection_id>/datasets/<dataset_id>` and `PATCH /dp/v1/collections/<collection_id>/datasets/<dataset_id>`, symmetrical to the existing `PATCH /curation/v1/collections/<collection_id>` for updating collection metadata) 
        - Must have auth gating this action to owners / super curators
        - Action must ONLY be valid if dataset_id is a dataset in an unpublished collection AND it has a successful processing status 
- Response: 202 (Accepted) status code response on successful queueing of update seems sufficient w/o additional body, plus typical error statuses + messages for input validation errors or backend errors that are caught.
- The endpoint (or downstream business layer function that endpoint calls) will validate inputs and trigger the existing batch job in `dataset_metadata_update.py` by calling the existing`trigger_dataset_artifact_update` in the business layer. This will kickoff metadata updates to all artifacts and the DB, and update dataset status accordingly.
- Request schema should be valid uns dict fields available for update via endpoint, mapped to their new desired value (i.e. `{"title": "new title"}`)
        - "title" must be supported. Others to consider: Citation, default_embedding, batch_condition, adding a new field. Design with extensibility in mind, but do not implement anything other than dataset title changes yet.

FE Design: 
- Use endpoint above, connect to UX designs (links currently dead, reach out to Harley/Brian)

**Comment by nayib-jose-gloria** [comment]
Backend Estimate: 1-2 weeks x 1 engineer + 1 reviewer

- Create endpoint in both the Curation and DP APIs for patching dataset metadata such as dataset title (i.e. `PATCH /curation/v1/collections/<collection_id>/datasets/<dataset_id>` and `PATCH /dp/v1/collections/<collection_id>/datasets/<dataset_id>`, symmetrical to the existing `PATCH /curation/v1/collections/<collection_id>` for updating collection metadata) 
        - Must have auth gating this action to owners / super curators
        - Action must ONLY be valid if dataset_id is a dataset in an unpublished collection AND it has a successful processing status 
- Response: 202 (Accepted) status code response on successful queueing of update seems sufficient w/o additional body, plus typical error statuses + messages for input validation errors or backend errors that are caught.
- The endpoint (or downstream business layer function that endpoint calls) will validate inputs and trigger the existing batch job in `dataset_metadata_update.py` by calling the existing`trigger_dataset_artifact_update` in the business layer. This will kickoff metadata updates to all artifacts and the DB, and update dataset status accordingly.
- Request schema should be valid uns dict fields available for update via endpoint, mapped to their new desired value (i.e. `{"title": "new title"}`)
        - "title" must be supported. Others to consider: Citation, default_embedding, batch_condition, adding a new field. Design with extensibility in mind, but do not implement anything other than dataset title changes yet.


FE Design: 
- Use endpoint above, connect to UX designs (links currently dead, reach out to Harley/Brian)

**Comment by nayib-jose-gloria** [comment]
Requires agreement with product on API endpoint names + updated spec before merging code
