### ISSUE TITLE
Our documentation explains what cellxgene is for and how to use it.

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#158]
### Goal: 
* Cellxgene has a single landing page linked to our product porfolio that explains what our products are for and how to use them. 

### Implementation: 
* We will update the cellxgene documentation site and re-host it using gitbooks. Proposed updates are listed [here](https://docs.google.com/spreadsheets/d/193N8O-cXzkVQNhxNY99sOtxYhV6m9dtBJsn9yPRSrUA/edit#gid=0).

**Comment by MaximilianLombardo** [comment]
Adding link for the current 'live' new version of the docs site:

https://app.gitbook.com/@maximilian-g-lombardo/s/cellxgene-docs/
