### ISSUE TITLE
Scientists can download annotated expression matrices from the portal dataset-view

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#16]
**Story**

**Scientists can download datasets in AnnData, Loom, or Seurat v3 RDS formats. Computational Biologists want to be able to download datasets from the _dataset-view_ so they can apply analyses that are unavailable in _Explore Data_.**

Until portal _project-view_ of datasets is available, the portal _dataset-view_ must be updated to support the following downloads:

For the remix dataset, the formats are:
* AnnData
* Loom
* Seurat v3 RDS

Per the discussion during the August 14 Sprint Planning session, the original dataset will not be present on the portal - striking this requirement.

~~For the original dataset the format is limited to one standard format:~~
~~* H5AD - because the curation process creates an H5AD as part of creating a CXG~~

Per the discussion during the August 18 Refinement session, downloads MUST be **resumable** based on the dataset sizes currently curated (7 GB). The download capability will be delivered in two increments:

1. Non-resumable download from the UI and a resumable download via a copy-n-paste _curlable_ script. If the download is interrupted, the user will need to restart. (See [snippets](https://www.hashbangcode.com/article/some-useful-curl-snippets)).
2. [Resumable Download from the UI](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/33)

---

[Earlier designs from Lia, including download flow with _curlable_ URLs](
https://www.figma.com/proto/aI3bt6MRFJODNnI4q9DGN8/9-Browser?node-id=362%3A382&viewport=-30080%2C579%2C1&scaling=min-zoom)

---

*DCP style*
![DCP Download Style.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/27aff235-b0cb-4b85-acae-097186ed55d2)

**Comment by pdugan20** [comment]
I'm imagining that we could have an action that could be accessed from within the row of the dataset table which would trigger some type of interstitial (possibly a modal or drop down) which provided different download mechanisms.

I'll discuss some more with @liaprins-czi based on her initial work in this area.

**Comment by liaprins-czi** [comment]
@pdugan20 Here are a few explorations of this sort of behavior I did for DCP 2.0 a while back; we can discuss more in person if helpful! Just figured I would share these concepts:

https://www.figma.com/file/eBleafBDoIOOUmyRI33RVN/1-Browser?node-id=79%3A0

https://www.figma.com/file/eBleafBDoIOOUmyRI33RVN/1-Browser?node-id=0%3A1

**Comment by brianraymor** [comment]
@tihuan - Thoughts related to refinement:
- The existing [POST /v1/dataset/{dataset_uuid} ](https://app.zenhub.com/workspace/o/chanzuckerberg/corpora-data-portal/issues/476)issue addresses BE implementation.
- There needs to be a related FE issue created in corpora-data-portal and added to this epic. That new issue should takes a blocking dependency on the UX issue - [Design interim solution for downloading expression matrices](https://app.zenhub.com/workspace/o/chanzuckerberg/single-cell/issues/17).

**Comment by tihuan** [comment]
Thanks @brianraymor ! FE issue created 🎉 

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/518

**Comment by pdugan20** [comment]
Working on the UI for this now. I'm assuming to start with that we'll allow users to download a single format at a time, from the 4 different formats outlined above. Is that correct?

Also I'm assuming we'll be able to generate the dataset download in real time, vs requiring some amount of time between a user clicking download and the download actually being available. Is that also correct?

**Comment by brianraymor** [comment]
@mckinsel can correct or amplify as needed.

_ I'm assuming to start with that we'll allow users to download a single format at a time, from the 4 different formats outlined above. Is that correct?_

Yes.

_ I'm assuming we'll be able to generate the dataset download in real time, vs requiring some amount of time between a user clicking download and the download actually being available. Is that also correct?_

Yes. These should be _precooked_ and _ready to eat_.

For example - see a similar design in the [DCP portal](https://data.humancellatlas.org/explore/projects/4a95101c-9ffc-4f30-a809-f04518a23803/m/expression-matrices).

**Comment by pdugan20** [comment]
Perfect! Thanks for the points of clarification.

**Comment by brianraymor** [comment]
Per the August 18 Refinement, added a requirement for **resumable** downloads.
