### ISSUE TITLE
Data consumers can easily discover and review metadata for a dataset in cellxgene explorer

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#171]
**Story**

_Data consumers can easily discover and review metadata for a dataset in cellxgene explorer._

The [dataset drawer](https://github.com/chanzuckerberg/cellxgene/issues/1319) in cellxgene explorer was designed to share [ schema metadata](https://github.com/chanzuckerberg/single-cell-curation/blob/main/docs/corpora_schema.md) for a dataset. Originally, this included both collection and dataset metadata, but collection metadata was [deprecated](https://github.com/chanzuckerberg/single-cell/issues/75) in `v1.1.0` of the schema. The dataset metadata duplicates features in the portal _A Collection_ view which has columns for the most important metadata: `Tissue`, `Assay`, `Disease`, and `Organism`. 

The original design was extended to include [singleton categories](https://github.com/chanzuckerberg/cellxgene/issues/1319#issuecomment-683953302). There is an open question of whether these values need to be surfaced.

@pablo-gar [also reported](https://chanzuckerbergteam.slack.com/archives/C01JTQUJN81/p1616791258062700) that the `ontology ID` for `organism` is always empty. 

The drawer is not discoverable by consumers. No publisher has inquired about "missing" metadata for either case during pre-production reviews. A redesign and user review is required.

**UX Design**
[Design](https://www.figma.com/file/egBWq3OCAgnVoWi8Dq8bMu/Seamless-Experience?node-id=253%3A2648)
[Prototype](https://www.figma.com/proto/egBWq3OCAgnVoWi8Dq8bMu/Seamless-Experience?page-id=253%3A2647&node-id=253%3A2648&viewport=462%2C620%2C0.426982581615448&scaling=min-zoom)

**Comment by brianraymor** [comment]
@hthomas-czi - The current UX design separates some ontologies from their labels. For example, `PATO` (the ontology) is listed separately from the `Disease` label. `Uberon` is the ontology for Tissue. What's the rationale for this design in comparison to using a hover for a label to display its ontology or the status quo which has an ontology column:

![Screen Shot 2021-05-03 at 3.14.48 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/975e1018-5c89-4f67-bd66-2e8c31ff7850)

**Comment by hthomas-czi** [comment]
@brianraymor No good reason. I sketched out two more concepts. What do you think about these? 
![Screen Shot 2021-05-03 at 4.05.11 PM.png](https://images.zenhubusercontent.com/5f7362d2ffe2db448b7761ff/ed986bb5-fa3d-4b52-97ba-d7807fdbf5fe)

**Comment by brianraymor** [comment]
I prefer the _hover_ for the ontology (when available) which is what we discussed potentially for the left sidebar in the future.

**Comment by brianraymor** [comment]
@hthomas-czi - why is `organism` included with collection information rather than the dataset metadata? Similarly, do you want the other collection links (titled `Project Links`) to be separated out from the collection information including the `DOI` link?

**Comment by hthomas-czi** [comment]
@brianraymor Good questions. What do you think about this design? 
<img width="633" alt="Screen Shot 2021-05-04 at 10 16 25 AM" src="https://user-images.githubusercontent.com/72052788/117043311-e96f8e80-acc1-11eb-948f-955c24468e26.png">

**Comment by brianraymor** [comment]
@hthomas-czi - better, but wouldn't we want to observe the [link ordering](https://github.com/chanzuckerberg/single-cell/issues/124) that we established in collections - so `Contact` before `DOI` for example?

If we're including collection `Description` should we truncate? Some of the descriptions are quite lengthy.

For the dataset metadata, what is the ordering? It looked sorted until `Organism` was added to the top.

**Comment by hthomas-czi** [comment]
@brianraymor 

> better, but wouldn't we want to observe the link ordering that we established in collections - so Contact before DOI for example?

Good call.

> If we're including collection Description should we truncate? Some of the descriptions are quite lengthy.

Agreed. I'm thinking we could truncate at four lines, but don't have a strong opinion.

> For the dataset metadata, what is the ordering? It looked sorted until Organism was added to the top.

I was just following the current ordering but now that you mention it, it does seem to be alphabetical except for "Organism." My best guess is that was considered more important than everything else? I think it makes sense to keep it all alphabetical.

![Dataset Drawer](https://user-images.githubusercontent.com/72052788/117050972-dd3bff00-acca-11eb-93bc-f4b0eb540804.png)

**Comment by brianraymor** [comment]
During the June 14 meeting, we reviewed potential ways to improve the _discoverability_ of the dataset drawer:

1. Open the dataset drawer by default when a user is referred to a CXG from an external site (rather than the cellxgene data portal)
1. Move the `i` menu button - perhaps closer to the dataset *breadcrumb*

No action required at this time.
