### ISSUE TITLE
The Data Source link from the related Collection must be surfaced in cellxgene explorer

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#172]
Per an external agreement, **the `Data Source` link from the related Collection MUST be surfaced in cellxgene explorer** to allow data consumers to access the external portal that is the data source for the visualization. That external portal may have additional information or links to other visualization software.

---

**UX Design**

[Design](https://www.figma.com/file/egBWq3OCAgnVoWi8Dq8bMu/Seamless-Experience?node-id=255%3A181)

- Update menu iconography
  - [Documentation](https://www.figma.com/file/egBWq3OCAgnVoWi8Dq8bMu/Seamless-Experience?node-id=296%3A3611)
  - [GitHub](https://www.figma.com/file/egBWq3OCAgnVoWi8Dq8bMu/Seamless-Experience?node-id=296%3A3618)
  - [Slack](https://www.figma.com/file/egBWq3OCAgnVoWi8Dq8bMu/Seamless-Experience?node-id=296%3A3602)
- Move `version`, `MIT License`, `Terms of Service`, and `Privacy Policy` to `About` submenu

---

**Prototype**

The UX can be populated using the private portal REST API or using hardcoded values.

*REST API*

There is currently no query to directly return the Data Source for a CXG, but it is possible to use `GET /dp/v1/collections/{collection_uuid}` to match the CXG URL with `dataset_deployments`:

```
     "dataset_deployments": [
        {
          "environment": "string",
          "id": "string",
          "url": "string"
        }
      ],
```

and then access:

- the links for a collection including `Data Source`

A python notebook can be provided that demonstrates the REST API and the steps required. 

*Hardcoded values*

For consistency in the prototype, a Tabula Muris Senis example is used:

| Data Source Name | Data Source URL |
|-|-|
| 'Tabula Muris Senis' | 'https://tabula-muris-senis.ds.czbiohub.org/' |

**Comment by hthomas-czi** [comment]
@brianraymor Should we expand this epic to include the overall menu improvements (e.g., updated icons, nesting "About") as well?

**Comment by brianraymor** [comment]
@hthomas-czi - could you include those specific details in the UX section?

**Comment by hthomas-czi** [comment]
Added. Let me know how that looks @brianraymor

**Comment by brianraymor** [comment]
@hthomas-czi - per discussion with Clever Canary on May 24, the preference was for you to design a new glyph to represent `Data Source` menu items rather than:

1. Allowing the publisher to provide an image which may have quality or scaling issues
2. Using favicons from the domain of the `Data Source` which may also have quality or scaling issues

**Comment by brianraymor** [comment]
Agreed during the June 14 meeting to remove the `Data Source` from the cellxgene menu and ONLY surface in the dataset drawer.
