### ISSUE TITLE
Transfer repository to chanzuckerberg github organization.

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#193]

**Comment by ambrosejcarr** [comment]
@MaximilianLombardo We can use this public chanzuckerberg github repository: https://github.com/chanzuckerberg/cellxgene-documentation

**Comment by MaximilianLombardo** [comment]
Thats great - will sync this up after the final edits have landed!

**Comment by ambrosejcarr** [comment]
Have uploaded gitbook data to cellxgene-documentation. Waiting on OAuth approval for gitbook on chanzuckerberg github organization. 

Continue here: https://app.gitbook.com/@chanzuckerberg/s/cellxgene-documentation/~/settings/integrations
Check status here: https://github.com/settings/connections/applications/c9c25e33d347c9b960e3

**Comment by ambrosejcarr** [comment]
Complete. Documentation is available at https://github.com/chanzuckerberg/cellxgene-documentation
