### ISSUE TITLE
Scientists can create private dataset-specific annotations on hosted cellxgene

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/single-cell#20]
#### A scientist must be able to create new annotations for a dataset so that they can describe the data they are exploring

**sub-story: A scientist must be able to create and delete categories and edit the category name.**

REQ: Annotations function like categories. Category names are unique and validated by the cellxgene client. This means, for example, that category like "color by" must also work for Annotations. 

**sub-story: A scientist must be able to create and delete labels within categories and edit the label name so that they can capture individual descriptors of observations (cells) they are exploring"**

**sub-story: A scientist needs changes they make to annotations to be automatically saved every few seconds so that their annotations persist across refreshes and sessions**

REQ: CLI control of user annotations on desktop cellxgene continues to function as before (actual parameters may change, but features must remain available). Specifically: 
- It must be possible to disable annotations (currently --disable-annotations) 
- A single user must be able to specify the CSV file that annotations will be stored in (currently --annotations-file)
- It must be possible to specify an output directory for annotations when cellxgene automatically generates annotations files (currently --annotations-dir)

REQ: When desktop cellxgene is started with annotations enabled but without --annotations-file specified: 
- Each visitor must continue to receive a long-lived session cookie. 
- Annotations must continue to be saved into a file that associates with their cookie and the dataset being explored. 
- The User must continue to be informed of their file name. 

REQ: Annotation operations must not take more than 1000ms, and should optimally take 100ms. 

### See Also

[Annotations Design Doc](https://docs.google.com/document/d/1D_AqL-TKtFmjBP6zSaXZfnaf4Rk_6wWoLkZYGqcoXXE/edit?pli=1#)

**Comment by brianraymor** [comment]
Per August 16 Refinement - #1689 and #493 are removed - to be added to a "Deletion" epic.
