### ISSUE TITLE
Update contribution guidelines for cellxgene

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#202]
### Story

_A developer who wants to contribute to cellxgene desktop, or the cellxgene data portal understands how to contribute to our project, our expectations of contributions and contributors, how to determine whether we will accept a contribution, and what support we offer (and do not offer) as a part of the contribution process._

### Implementation

* [This page](https://chanzuckerberg.github.io/cellxgene/posts/contribute) should be updated to enable the above story.

**Comment by signechambers1** [comment]
This is complete, updated here: https://github.com/chanzuckerberg/cellxgene-documentation/blob/main/contribute.md
