### ISSUE TITLE
Publisher Experience – Create collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#21]
**Requirements**
- Collection Name, Collection Description, Contact Name, Contact Email
- Optional Links of type `DOI`, `Raw Data`, `Protocol`, `Lab Website`, or `Other`
- User can agree to Data Portal submission policy and click "Learn more" to show policy

Figma: https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=55%3A727

Reference: https://github.com/chanzuckerberg/corpora-data-portal/issues/364

---

@pdugan20 commented on [Wed Jun 10 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/364#issuecomment-642132572)
This page will probably share some common components with the existing project management page (where fields are common and remain editable post-creation).

It should allow for:

Naming of a project
Ability to add a dataset to the project
Accommodate whatever other input is required on behalf of users

---

@liaprins-czi I'm imagining we'd want to keep this page as simple as possible and push secondary actions like adding additional users to a project in subsequent post-creation steps? Maybe a step like an empty-state checklist which allows users to complete follow-up actions?

---

@liaprins-czi commented on [Wed Jun 10 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/364#issuecomment-642222427)

Yeah, I think keeping it as simple as possible, too! Here is something I had posted in #364 but I think it's more relevant for this issue:

_This is what I've been exploring a bit in sketches earlier this week. My initial thought was that when a user is creating a new project, it could make sense to walk them through what they can add/required to add (dataset(s), project-level metadata, and settings for when the publish it like private vs public, etc). But when I sketched that out I wasn't so sure. Especially since user can just add a dataset, and we pull out the project-level fields from it if they're included. I think the overarching goal of getting it to be as easy and quick for the user as possible (to prevent them from dropping off from contributing their data) will help to decide. I also want to see how many project-level fields end up making it into our initial schema (which should be finalized Jun 12)._

As far as "adding additional users to a project": for MVP it was just going to be allowing one user to go into the create/manage state of a project (same user that created the project has to edit it). They can get a link for a private project they made, to share with others and they'll be able to see a preview of the project page, cxg visualizations, etc. But if you think it's important for multiple users to access a project's manage state for MVP, we can push back on that initial decision.

---

@pdugan20 commented on [Thu Jul 30 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/364#issuecomment-666544471)

OK have some early work around creating a project and uploading a dataset here: https://www.figma.com/file/ldTQ4rQu0wYR6fSXJtjDhf/project-management?node-id=0%3A1

...and will plan to discuss at our design review later today. I'm hoping to gain more clarity around:

- required fields (aside from project name)
- whether or not a user can upload one or more dataset files as a part of a single project
- whether or not we plan on associating each project with a user id in order to show a list of a users projects that they have created (and can edit)
- does a project need to exist before a dataset can be uploaded?
- are we supporting: a. file uploading directly in the browser, b. copying a link to a dropbox file or other data service, c. both?

I believe we also have a list of minimum columns each dataset must contain, correct? So we'll probably want to create some robust error states here that explain to a user how to modify and reupload their dataset if it doesn't meet our minimum requirements.

**Comment by brianraymor** [comment]
@pdugan20 - Per the September 29 refinement for self-publication:

- Add *Links* to the **Create Collection** flow. The [schema](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/backend/schema/corpora_schema.md) supports the following fields:

Additionally, submitters may include project-level metadata inside their dataset. This information is used to populate project metadata in Corpora when the submitted dataset is used to create a new project. 

**Field name**|**Description**
:--|:--
project\_name|String
project\_description|Longer description of the project.
project\_links|List of links associated with the project.

Much of the project metadata is links. Each link is a dictionary with keys "link_url", "link_name", and "link_type".
"link_name" gives the text that should be displayed for the link. "link_type" is one of `PROTOCOL`, `RAW_DATA`,
`SUMMARY`, or `OTHER`. Exactly one link should be of type `SUMMARY`.

- Add attestation to the **Create Collection** flow for private Collections

**Comment by hthomas-czi** [comment]
Figma: https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=0%3A1
