### ISSUE TITLE
Publishers want to create a private collection for related dataset submissions

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#23]
**Definitions**

From the [2020 plan](https://docs.google.com/document/d/13KbnfQVruyEp5JbeTbhelYejroqBHn2jtW0YbRnAx0I/edit?ts=5eb1f951#heading=h.zgkb14f7z8qq):

1. A project represents one or more datasets submitted by the same publisher and identified by the publisher as belonging to the same collection, which is conventionally assumed to be a "unit of publication".  Commonly this will be a collection of highly-related datasets belonging to a single paper, eg, the Tabula Muris Senis collection, the Gut Cell Atlas, etc. 
2. A dataset must belong to exactly one project.

In other words, a dataset is like a song and a project is like an album. See [a project page](https://data.humancellatlas.org/explore/projects/f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc) in the DCP Portal for one example.

**Stories**

_Publishers want to create a private collection of related dataset submissions belonging to a publication_.

// Need to merge these duplicate stories from the 2020 plan:

- _Scientists who host pre-publication data on Corpora want their data to be private until their dataset has been peer reviewed so they have a chance to fix errors before the data are widely viewed._ 
- _Scientists who provide us data want an opportunity to review their submission before it is publicized._

**Design**

The Schema currently allows an optional set of [project related fields](https://docs.google.com/document/d/1_I2dnYuCTvO2yABR0FnLRnI8RnMhiASC5Ny4ZwDjsCI/edit#bookmark=id.o2f1dl8rft6p
) to be included in the dataset metadata. Historically, this is required to provide information for the human curator.

The fields are:
- project_name
- project_description
- project_protocol_links
- project_raw_data_links
- project_other_links

In self-publishing, this information is gathered in the UI when a publisher creates a collection. These fields can then be deprecated from the schema. (Updates to the current data model will also be required.)

For the portal design:

- Collection name is required.
- Collection description is required.
- Collection contact is required.
- All other Collection fields are optional.

- By default, new Collections are private to the Publisher.

---

**UX Design**
Collection view
- All collections should display title, contributors, preprint_doi, publication_doi, organisms, tissues, assays, and the total number of cells measured for all datasets in the collection 

Dataset view
- Page should show collection title and description
- Each dataset should display organisms, tissues, assays, and the total number of cells measured for all datasets in the collection

[Figma](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Collections?node-id=55%3A727)

[Reference](https://github.com/chanzuckerberg/corpora-data-portal/issues/364)

**Comment by brianraymor** [comment]
Blocked on the outcome of the discussion on[ portal](https://chanzuckerbergteam.slack.com/archives/C013CER6C7N/p1597375808151700).

**Comment by signechambers1** [comment]
[#975](https://github.com/chanzuckerberg/cellxgene/issues/975) describes a related use case
