### ISSUE TITLE
Create documentation on best practices/how to develop for integrated Explorer/Portal

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/single-cell#232]
Historically, the development of Explorer and Portal has been disjoint -- one could work on developing features for one app without thinking too much about the impact of the other. Over time, the two apps have become more intertwined and as such, the architecture will be moving more towards a microservice-based architecture.

In order to accelerate onboarding for new engineers and to share best practices around development for this larger system, we would like to create some documentation on how an engineer can develop new features for the applications and ensure that that the other is working as expected. This documentation should also be helpful for engineers that are working on building out features that span both applications.

As part of creating documentation on best practices for setting up an environment to develop across the two apps, we can also consolidate individual READMEs to set up the dev environment into this single doc page.

Definition of Done: Create a new page in `/how-we-work` that discusses the above. Remove any duplicate information from READMEs in other repos.

**Comment by atolopko-czi** [comment]
This would include all infra & ops docs, covering deployment, Terraform, testing, etc.?

**Comment by maniarathi** [comment]
Deprecating this ticket as we have updated instructions from the [Onboarding doc](https://docs.google.com/document/d/1yUq8myuLpwBGfQjAXeAsvfWYXdoJuWJebI3QJdetQJQ/edit).
