### ISSUE TITLE
Add Optional "Batch" field to schema

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#24]
[Pending design conversation](https://chanzuckerbergteam.slack.com/archives/G012TNF4C87/p1598917525006400)

Normalization and integration methods perform better when conditioned on the "batch" that data were produced in, as different batches tend to vary due to technical (nuisance) factors. 

Enable users to capture batch information in the cellxgene schema. 

cc @mckinsel

**Comment by bkmartinjr** [comment]
+1  Will be important for most of the integration/harmonization methods (eg, both scArches and scANVI rely on batch labels to condition their networks).

**Comment by brianraymor** [comment]
Closing as duplicate to the schema issue in single-cell-curation.
