### ISSUE TITLE
What to do about embiggened datasets?

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#245]
### Background

We have a 4 million cell dataset which hosted cellxgene explorer can't handle. It triggers page-unresponsive warnings in cellxgene and generally does not perform adequately. We don't want to launch with this dataset because it produces a bad experience.

- The dataset is published. 
- The authors are excited about being able to provide access to the full dataset in our standard schema
- The authors are excited about users being able to view a subset of the data and explore it using cellxgene. 

We believe that datasets will continue to increase in size due to integration (this is not the final occurrence)
Being able to download standardized datasets and being able to explore them have distinct value.

#### Portal

- Disable exploration of datasets in the portal larger than 2 million cells (gray out icon)
- Hover over grayed out icon states "Exploration is currently unavailable for datasets with more than 2 million cells"
- Dataset exploration is disabled privately and publicly if they contain > 2m cells.
- Intent for tooltip should be .warning

#### Explorer

- Filter datasets larger than 2 million cells from the seamless menu in explorer

#### Curation

- Indicate in submission documentation that datasets larger than 2m cells will not be explorable. Stanford to communicate to users about limitations of exploration

#### Metrics
- Amanda to add this metric to the metrics reporting she is creating.

### Future

Investigate solutions for increasing our performance ceiling. Could include: 

1. subsampling datasets
2. improving explorer performance so that it can display more points
3. displaying manifolds instead of individual cells

--- 

Capturing Mim's recommendation from [**eng**](https://czi-sci.slack.com/archives/C023Q1APASK/p1634074295301200):

> It  might be better to filter on the BE if it’s required longer term. **Another option could be to filter on the FE but have the limit specified by the BE**. I can add the filter on the FE for now and we can revisit post-launch if needed.

**Comment by brianraymor** [comment]
See [**wrangling**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1659730071728089).

@signechambers1 @ambrosejcarr - I would be curious about your perspective about whether we should mirror the curation UX policy - [Do not include datasets larger than 2 million cells in the dataset menu](https://app.zenhub.com/workspace/o/chanzuckerberg/single-cell-explorer/issues/141) - and block access to the `explorer_url` (filter it out) in the curation API (and all other portal APIs that return the reference to the CXG URL.

My personal position is to take no action since it's currently an edge case and scaling is to be addressed soon.

Note that we do make independent policy decisions for the API and the UX. For example, we do not allow publication or collection deletion from the API - only the UX.

**Comment by ambrosejcarr** [comment]
> scaling is to be addressed soon

We are addressing UI issues that degrade performance on datasets [up to 2 million cells](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/327). I don't believe the 4m cell dataset will be addressed anytime soon. 

While we're not aware of any dataset > 2m cells, I do imagine submitters will continue to submit data as single objects - so if we receive large datasets in the future, they will create additional instances of this issue.

**Comment by signechambers1** [comment]
Thanks for raising Brian! Echoing Ambrose, our performance related goals
for this quarter are for up to 2M cell datasets so we won't be enabling
explorer for 4M cell datasets anytime soon.

My thoughts probably depend on the use cases for the curation API. What is
the main use case for the explorer url in the curation API? I could imagine
it is for curators to see what users would see? If so, blocking that option
for datasets >2M cells would make sense to me so as not to mislead anyone
that users will see an explorer UI but agree that is low priority since it
is an edge case.
