### ISSUE TITLE
Write RFC for upload from services and resumable uploads

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#25]
---

@maniarathi commented on [Wed Jun 10 2020](https://github.com/chanzuckerberg/corpora-data-portal/issues/361)

Had a short conversation with Marcus about this and [Calvin brought it up in a code review](https://github.com/chanzuckerberg/corpora-data-portal/pull/336#discussion_r437748997
), but we should try to support the more common methods of large file upload that contributors feel comfortable with in a way that also reduces latency. This ticket is a spike to investigate that and come up with the first upload mechanism for large files (note the REST API as it is implemented today can only handle small files). 

A starting point is Marcus mentioning that Dropbox is a common mechanism to store large files; we could implement a system by which contributors specify a Dropbox URL and we spin up a small instance to download the file and upload to S3 automatically. 

Might investigate [multcloud](https://www.multcloud.com/tutorials/move-files-from-one-server-to-another.html)

---
[resumableJS](http://resumablejs.com/)

A JavaScript library providing multiple simultaneous, stable and resumable uploads via the HTML5 File API

[Plupload](https://www.plupload.com/)

Plupload is based on multi-runtime pollyfills for XMLHttpRequest L2, File and Image APIs.

---
The [Google Drive upload API](https://developers.google.com/drive/api/v3/manage-uploads#top_of_page) and [Cloud API ](https://cloud.google.com/storage/docs/performing-resumable-uploads) include patterns for multipart and resumable uploads.

---

**Comment by brianraymor** [comment]
@tihuan says:

IDSeq is actively exploring resumable **upload** right now with their intern Kevin!

Current work:

[Doc](https://czi.quip.com/Rop4AeVDQi63/Upload-limit-CLI-Email-copy)
[Wireframes](https://chanzuckerberg.invisionapp.com/share/HVYB72WQE54#/screens/428373894)
Slack channel: #proj-idseq-uploads

Approach: CLI for upload + Web UI for entering metadata

Charles and I are wondering if it's worth for IDSeq and cellxgene to collab on this feature in any capacity?

**Comment by lesliecodes** [comment]
Upload from service first, then look at resumable upload

**Comment by Bento007** [comment]
# Multicloud
We will need to have a dropbox account for cellxgene where the users can share their files. Then we can automatically upload those files to s3

# Lambda
Given a direct link to the file to download, we can upload the file from the file from the lambda to s3. This has been test for files as big as 1.5GB. Since there is 15min timeout for lambdas, if the file is not uploaded before then, the upload will fail. This can be fixed by using a dedicated server to perform the upload, or fargate with docker images.

We will also need to determine how to download each file from the shared url. It could be different for each storage platform.

## drop box
https://help.dropbox.com/files-folders/share/force-download

**Comment by tihuan** [comment]
Really awesome investigation! Thanks so much, Trent! 

Almost hoped that AWS had a service to transfer 3rd party storage services to S3 for us already. Sounds like a pretty compelling service lol I'll ask #help-aws channel too just to be sure!

**Comment by Bento007** [comment]
# Multipart Uploads
https://www.altostra.com/blog/multipart-uploads-with-s3-presigned-url

**Comment by Bento007** [comment]
For large files >5GB there is no way around needing a BE server to act as an intermediary to upload files to s3, this is because of the way S3 does multipart uploads. To avoid needing to create multiple solutions, we should create a server that works for both multipart uploads and single part uploads.

**Comment by Bento007** [comment]
For client side upload of large files, we can generate temporary STS credentials to upload the file. From there the browser can use AWS JS SDK to upload the file in multiple parts. This uploaded process is resumable. See https://github.com/aws/aws-sdk-js/issues/1603#issuecomment-431581699

**Comment by Bento007** [comment]
For multipart uploads from cloud to cloud, we will need to download the file to a server and them upload the file in multiple parts to s3.

**Comment by Bento007** [comment]
We will also need to create some lifecycle policies on our S3 bucket to cleanup incomplete multipart uploads after a certain period of time.

**Comment by Bento007** [comment]
## Resumable uploads
Resumable upload will give users the ability to upload files in parts, and continue uploading where they left off without in case of failure. There are a number of JS libraries that help mak

**Comment by maniarathi** [comment]
Heh, you might want to take a look at the old upload-service code. A lot of what you describe above... well, we (read: Parth and Sam) solved for, such as multipart uploads, using 5GB as a cut-off for whether to use Lambda or Batch, checksumming to ensure that the file hadn't gotten corrupted on the way, creating a temporary "upload area" to hold files until they were moved to their final destination and then cleaning up of the "upload area."

**Comment by tihuan** [comment]
Design presentation on Monday!
