### ISSUE TITLE
Add curator info to GET /collection/{collection_uuid} endpoint

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell#259]
In order to support the new curator row displayed in the collection info, additional information will need to be return in in the GET /collection/{collection_uuid} endpoint. The information that needs to be added to the endpoint response are the curators email, first name, and last name. These fields are not stored in the data portal database. They are found in Auth0 using the foreign key Owner in the collections table. The owner of the collection is also the curator of the collection.

## Approach
- Retrieve the curator's information from auth0 using [Auth0's API(https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id).
- Add the following JSON into the return response from GET /collection/{collection_uuid} response. 
```
{ 
  "curator": {
    "email": "string",
    "last_name": "string",
    "first_name": "string"
  }
}
```

## Definition of Done
- GET /collection/{collection_uuid} returns the collection curators email, last name, and first name.

**Comment by brianraymor** [comment]
Is there a rationale for why this design does not reuse the pattern for contact?

```
 "contact_email": "string",
  "contact_name": "string",
```

**Comment by brianraymor** [comment]
Issue moved to [chanzuckerberg/single-cell-data-portal #1661](https://github.com/chanzuckerberg/single-cell-data-portal/issues/1661) via [**ZenHub**](https://www.zenhub.com/)
