### ISSUE TITLE
Polishing the seamless experience

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#260]
### Summary

With the release of [cellxgene offers a consistent and seamless experience for consumers](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/143), there have been suggestions for refinements that are collected in this epic to consider in a future comprehensive design update.

---

1. When there’s **one** dataset in a collection and the breadcrumbs are zoomed in, it looks like there’s an errant “Dataset”. Clicking on it does nothing for example. This may perplex a user.

![Screen Shot 2021-10-14 at 4.36.57 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/8d8f8d04-97e8-495f-8bf0-a74c34729b56)

compared to:

![Screen Shot 2021-10-14 at 4.38.59 PM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/dc82de75-800e-45fa-8478-7b004df8900e)

#### Design notes

@hthomas-czi wrote:

After thinking on this, it seems like the best solution is to simply hide the Dataset selector under the conditions you documented:

The collection contains only one dataset
The breadcrumbs are width-constrained

---

2.  The cellxgene Data Portal uses the cellxgene logo in the upper left to navigate to the portal home page. Explorer should reuse this pattern and remove the "Home" breadcrumb which requires zooming out to surface. 

3. The Explorer _hamburger_ menu only contains `Chat` and `About cellxgene`. It should be merged into the _?_ menu. 

#### Design notes

@hthomas-czi wrote:

I have a couple explorations around this idea.

![Explorer Navigation.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/7cd8bb7b-6577-4465-84e7-898751a9aa39)

I was trying to solve a couple problems here:

1. Use the cellxgene logo space more efficiently and consistently (to Brian’s point)
1. Move the orphaned menu bar items to the bottom right “Help” button where they belong
1. Provide enough space for the breadcrumbs so it shows up on smaller screens

Another concept:

![Explorer Navigation - Integrated.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/efe109b5-b98e-4b6f-9213-4594ed539dad)

**Comment by signechambers1** [comment]
Closing in favor of [#411](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/411) which captures the work discussed here.
