### ISSUE TITLE
CloudFront config cleanup

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell#276]
* Remove unused S3-hosted-cellxgene-<ENV> origin from all envs.
* Remove unused dev env CloudFront distributions (note these only exist for dev and not for staging or prod):
    * ​​E359J94I6J77GK: dev.single-cell.czi.technology
    * E2S00MTT4J9ATD: api.dev.single-cell.czi.technology
* Determine if clever canary distributions are still needed, and if not remove them:
    * EH1MJ6UQMILDN: canary-cellxgene.dev.single-cell.czi.technology
    * E25UUWE867SBZZ: api.canary-cellxgene.dev.single-cell.czi.technology
* Confirm w/team that the `S3-hosted-cellxgene-dev` origin in the cellxgene.dev.single-cell.czi.technology, cellxgene.staging.single-cell.czi.technology, and cellxgene.cziscience.com distribution is no longer needed. If so, remove.
* Document remaining CloudFront distributions in [Cellxgene Platform Technical Overview](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0)

**Comment by Bento007** [comment]
I updated the overview doc with links to the CloudFront resources in AWS and terraform

**Comment by Bento007** [comment]
complete
