### ISSUE TITLE
Update name and type for dataset_deployments

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#281]
I've never understood why `dataset_deployments` is an array since it simply contains the url for the CXG permanent link:

        "dataset_deployments": [
          {
            "url": "https://cellxgene.cziscience.com/e/aad97cb5-f375-45ef-ae9d-178e7f5d5180.cxg/"
          }

I would recommend the following changes:

1. The type should be a string (url) and not an array.
1. The name is not self-documenting. What is a "dataset deployments" to a curator?

@jahilton suggests:

`visualization_url` or `explorer_url`

**Comment by brianraymor** [comment]
For consistency with existing portal APIs, the name should be `explorer_url`.

**Comment by danieljhegeman** [comment]
Presumably this was introduced at a time when we anticipated datasets being hosted in various ways across multiple services.

> For consistency with existing portal APIs, the name should be explorer_url.

But it _is_ [consistent with the UI API](https://github.com/chanzuckerberg/single-cell-data-portal/blob/a967b3cc157987c6feecf305f077209a9485d470/backend/config/corpora-api.yml#L1348-L1354)... do you still want to make the change?

**Comment by brianraymor** [comment]
Yes please. The change to name and typing is consistent with **newer** APIs such as https://api.cellxgene.cziscience.com/dp/v1/datasets/index used in _filter by metadata_.

**Comment by danieljhegeman** [comment]
The change was made to `explorer_url` of type 'string'
