### ISSUE TITLE
Add collection_url to collections

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#282]
The `collection_url` should be added to collection metadata returned by both `GET /curation/collections` and `GET /curation/collections/{collection_uuid}`.

**Comment by danieljhegeman** [comment]
@metakuni pls submit PR against [this branch](https://github.com/chanzuckerberg/single-cell-data-portal/tree/review/curation-api-spec)

**Comment by metakuni** [comment]
Issue moved to [chanzuckerberg/single-cell-data-portal #2058](https://github.com/chanzuckerberg/single-cell-data-portal/issues/2058) via [**ZenHub**](https://www.zenhub.com/)
