### ISSUE TITLE
Add processing status for collection to GET /curation/collections

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#284]
For the summary/preview API - `GET /curation/collections` - the processing status could be a collection-level attribute indicating whether the collection and its datasets are in a "publishable" state.

Perhaps just:
`"processing_status": [FAILURE, PENDING, SUCCESS]`
at the collection-level with no per dataset status in datasets.

**Comment by danieljhegeman** [comment]
For a given collection, if some datasets have a status of `PENDING` and some have a status of `FAILURE`, which would you like to report for the summary status?

Contains       Summary
S                   S
P                   P
F                   F
SP                P
SF                 F
PF                 ??
SPF               ??

**Comment by brianraymor** [comment]
As a curator, I would want to be informed for failure cases so I could address while pending cases continued to process.

Contains => Summary
S => S
P => P
F => F
SP => P
SF => F
**PF => F
SPF => F

**Comment by jahilton** [comment]
>As a curator, I would want to be informed for failure cases so I could address while pending cases continued to process.

Agreed. If any datasets have a `FAILURE`, I would want the collection to be `F`.
