### ISSUE TITLE
Curators want to publish a private collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#29]
**Story**

_Curators want to publish a private collection on the portal to make it available for other scientists to explore._

This should be available in the collections page. It is only possible to set private to public. The reverse operation (public-> private)  is unavailable. 

`Publish` must be unavailable in a **private** collection under the following conditions:
1. The collection contains no datasets.
2. A dataset is being processed (upload, validation, conversion).
3. A dataset has a pending error condition such as a conversion failure.

Public collections in the _My Collections_ view do not include `Publish`. In the future, there will be [`Revise`](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/36). 

Note from August 19 Trust session:
Shawn recommends that publishers be reminded of the terms of service related to _derivative works_ when publishing a private collection. However, this is not required for curator scenarios. 

--- 

**UX Design**

[Figma](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=1487%3A1853)

**Comment by signechambers1** [comment]
[#875](https://github.com/chanzuckerberg/cellxgene/issues/875) potentially has relevant information

**Comment by tihuan** [comment]
Happy Monday, @brianraymor @hthomas-czi 🤩 Hope you had a great weekend!

Just wondering if we will have a copy for the text in the modal soon 😊 

Another user flow question, do we want to allow publishers/curators to make a collection public while a dataset is still being processed? (e.g., conversion is in WIP) What about if one format of a dataset conversion failed?

Thank you so much!

![Screen Shot 2021-01-11 at 9.40.41 AM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/d06cf01d-ea01-44dd-ad6b-a4b378c7b2dd)

**Comment by brianraymor** [comment]
_do we want to allow publishers/curators to make a collection public while a dataset is still being processed?_

Good question. Publishing must be disabled if a private collection is in an `error` or `in progress` state.

**Comment by tihuan** [comment]
Perfect thank you! I think one FE ticket should be enough. Will create it now!

@brianraymor are you working with @hthomas-czi on the modal text content? Thanks!
