### ISSUE TITLE
Add Plausible telemetry to landing page buttons

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#297]
## Telemetry to add

Below, section headers denote parts of the page, and bulleted lists denote the items for which instrumentation should be added. 

#### Nav Bar
* We're Hiring! 
* Help & Documentation
* Datasets
* Collections
* scExpression

#### Secondary Nav Bar
* Find single-cell data
* Explore gene expression
* Analyze datasets
* Download data
* Expedite collaboration

#### Quickly find the single-cell data you need
* Browse data collections

#### Explore gene expression across tissues and cell types
* See how it works

#### Execute on-demand interactive analyses of single-cell datasets
* Explore a multi-tissue atlas
* Explore the studies
* Browse tutorials

#### Download and integrate with zero wrangling
* Browse datasets for download
* Download with R
* Download with Python

#### Expedite collaborative data analysis
* Learn how it works

#### Publications
* Journal links
* BioRxiv links
* cellxgene links

#### Bottom bar
* Github
* Careers
* Contact us

**Comment by ainfeld** [comment]
**P1:**
Quickly find the single-cell data you need
- Browse data collections 

Explore gene expression across tissues and cell types
- See how it works

Execute on-demand interactive analyses of single-cell datasets
- Explore a multi-tissue atlas
- Explore the studies
- Browse tutorials

Download and integrate with zero wrangling
- Browse datasets for download
- Download with R
- Download with Python

**P2:**
Nav Bar
- Help & Documentation
- Datasets
- Collections
- scExpression (already instrumented)

Secondary Nav Bar
- Find single-cell data
- Explore gene expression
- Analyze datasets
- Download data
- Expedite collaboration

**P3:** 
Publications
- Journal links
- BioRxiv links
- cellxgene links

Expedite collaborative data analysis
- Learn how it works

Nav Bar
- We're Hiring!

Bottom bar
- Github
- Careers
- Contact us

**Comment by ainfeld** [comment]
If the `Tutorials` button in the drop down of `Help & Documentation` changes to the same link as the `Browse tutorials` under Execute on-demand interaction analyses of single-cell datasets that button name needs to be changed. 

Since the `We're hiring` and `Help & Documentation` aren't part of the navigation bar on other pages I didn't follow the same button naming structure for "Adding a tab to the navigation bar"

**Comment by ainfeld** [comment]
Per @maniarathi request, closing this issue and created a new issue within the single-cell-data-portal repo

**Comment by maniarathi** [comment]
Closing!
