### ISSUE TITLE
Add donor_id

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#308]
Note: This is a placeholder epic for Dev to add child issues following an assessment of required changes. 

The changes to the cellxgene-schema CLI are tracked separately in [cellxgene-schema must validate donor_id](https://github.com/chanzuckerberg/single-cell-curation/issues/261).

1. `donor_id` must be stored in the database similar to other dataset metadata.
1. `donor_id` must be returned in the curation API. @jahilton has confirmed that this field does not need to be included in the preview dataset metadata returned by [GET /v1/collections](https://api.cellxgene.cziscience.com/curation/ui/#/collection/backend.corpora.lambdas.api.v1.curation.collections.actions.get) but must be included in the detailed metadata returned by [GET /v1/collections/{collection_uuid}](https://api.cellxgene.cziscience.com/curation/ui/#/collection/backend.corpora.lambdas.api.v1.curation.collections.collection_id.actions.get).
1. `donor_id` must be displayed in *Standard Categories* or dataset drawer in Single Cell Explorer. For example,[the *Donor ID*  values under the LSB **Author Categories**](https://cellxgene.cziscience.com/e/b74100ea-1a1a-486a-9cad-70ae44150935.cxg/) would now appear as *donor id* values under *Standard Categories*.

**Comment by jahilton** [comment]
>is there value returning donor_id in the curation API?

Yes. If it's in our schema, then there will certainly be value in accessing the values via the API for evaluation

**Comment by ebezzi** [comment]
Two questions:
1. Do we also need to add donor_id to cellxgene-desktop as well as the explorer?
2. Do we need to add donor_id to the current FE filters in the portal?

**Comment by brianraymor** [comment]
`1`. I'm unfamiliar with any required changes for cellxgene **desktop**. @signechambers1 or @ambrosejcarr any comments? My  assumption is that no changes are required - if a consumer downloads the dataset and prepares it for desktop, then `donor_id` will simply appear in the LSB as expected. 

Note that for cellxgene **explorer**, you will need to add `donor_id` to [the list](https://github.com/chanzuckerberg/single-cell-explorer/blob/775e59fcf5c105bbe70edd17dbf1d2153c4f662c/client/src/common/types/entities.ts#L7) because categories are separated into presentation by Standard (cellxgene schema) and Author defined.

<img width="559" alt="Screen Shot 2022-08-15 at 10 28 17 AM" src="https://user-images.githubusercontent.com/3644743/184685200-e1666d4a-5b2b-4dff-9f2a-fa3ac90de342.png">


`2`. Not at this time.

**Comment by jychien** [comment]
Tested in rdev for sample test data with donor_id in "Standard Categories" and dataset drawer. Looks good.
