### ISSUE TITLE
Add suspension_type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#310]
Note: This is a placeholder epic for Dev to add child issues following an assessment of required changes. 

See [schema reference](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#suspension_type).

The changes to the cellxgene-schema CLI are tracked separately in [cellxgene-schema must validate suspension_type](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/273).

1. `suspension_type` must be stored in the database similar to other dataset metadata.
1. `suspension_type` must be returned in the curation and filter API(s). @jahilton has confirmed that this field must be included in the preview dataset metadata returned by [GET /v1/collections](https://api.cellxgene.cziscience.com/curation/ui/#/collection/backend.corpora.lambdas.api.v1.curation.collections.actions.get) AND the detailed metadata returned by [GET /v1/collections/{collection_uuid}](https://api.cellxgene.cziscience.com/curation/ui/#/collection/backend.corpora.lambdas.api.v1.curation.collections.collection_id.actions.get).
1. `suspension_type` must be displayed in *Standard Categories* or dataset drawer in Single Cell Explorer.

**Comment by jychien** [comment]
Tested in rdev with @ebezzi for suspension_type in "Standard Categories" and dataset drawer. Looks good. Test files can be found on dropbox: https://www.dropbox.com/sh/gdd38ecgwiolwaf/AAAMZYrCYviDRBo6feICvV49a?dl=0:
- rna_valid_v3.h5ad ([in prod](https://cellxgene.cziscience.com/e/e2a3c32d-71e2-4f38-b19c-dfcb8729cf46.cxg/)): suspension_type a mix of "cell" and "nucleus" in "Standard Categories"
- spatial_valid_v3_updated.h5ad ([in prod](https://cellxgene.cziscience.com/e/88b7da92-178d-4f27-bc18-b0165b256c67.cxg/)): suspension_type = "na" in dataset drawer
- atac_valid_v3_updated.h5ad ([in prod](https://cellxgene.cziscience.com/e/13a027de-ea3e-432b-9a5e-6bc7048498fc.cxg/)): suspension_type = "nucleus" in dataset drawer
