### ISSUE TITLE
"Demo atlas" of cellxgene scRNAseq datasets is publicly accessible via AWS S3 and the SOMA API

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#313]
See [1-pager](https://docs.google.com/document/d/14lgOMaUTU5syLEgzHEiZRzxpXyEjCak0aVZxCh-ALPE/edit#) for the motivation for this work.

**Comment by bkmartinjr** [comment]
@ambrosejcarr - who partners with me for schema design?  Can we add them to the issue, or have a dependent issue that defines the schema?

**Comment by ambrosejcarr** [comment]
I'm available to iterate with you on the schema and have added myself back to the issue. @brianraymor @jahilton would you like to be consulted on representation decisions for the single-mode scRNA-seq integrated dataset?

**Comment by jahilton** [comment]
@ambrosejcarr yes, please!

**Comment by brianraymor** [comment]
I would also like to be consulted.

**Comment by pablo-gar** [comment]
This work is progress, please see this doc for details

https://docs.google.com/document/d/19MfNp3E2S4wpzNzr-Q_S8SCVvxFZwYRc9XYzEUjBrVI/edit#
