### ISSUE TITLE
Investigate resumable downloads

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#32]
Per the August 18 Refinement, there was agreement that resumable downloads for matrices is required based on the dataset sizes that Marcus has observed during curation (7 GB for example). 

This has implications for the REST API and user experience designs.

**Food for Thought**

- [HTTP/1 Range Requests](https://tools.ietf.org/html/rfc7233#section-1)
- [DownThemAll](https://www.downthemall.org/howto/features/)
- [Background Fetch](https://wicg.github.io/background-fetch/) and [Background Fetch API: Get Ready To Use It!](https://medium.com/google-developer-experts/background-fetch-api-get-ready-to-use-it-69cca522cd8f)

**Comment by tihuan** [comment]
IDSeq is actively exploring resumable **upload** right now with their intern Kevin!

Current work:

[Doc](https://czi.quip.com/Rop4AeVDQi63/Upload-limit-CLI-Email-copy)
[Wireframes](https://chanzuckerberg.invisionapp.com/share/HVYB72WQE54#/screens/428373894)
Slack channel: #proj-idseq-uploads

Approach: CLI for upload + Web UI for entering metadata

Charles and I are wondering if it's worth for IDSeq and cellxgene to collab on this feature in any capacity?

**Comment by ambrosejcarr** [comment]
[Lia's Designs, including download flow with curlable URLs](
https://www.figma.com/proto/aI3bt6MRFJODNnI4q9DGN8/9-Browser?node-id=362%3A382&viewport=-30080%2C579%2C1&scaling=min-zoom
)

**Comment by brianraymor** [comment]
Per discussion with @tihuan and @mckinsel - _resumable_ downloads are paused until we have more signal from users.
