### ISSUE TITLE
Deletion of published data must be restricted

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#320]
### Context

See [**single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1683757407222789).

_Lead curators want to avoid accidental data loss by blocking the ability to use the Curation UX to delete:_

1. _Published collections_
1. _Published datasets_

_Lead curators want to avoid accidental data loss by blocking the ability to use the Discover API to delete:_

1. _Published datasets_

To this end, these features will no longer be available to authorized curators. 

Deletions must be requested by curators by creating an issue in the [single-cell-curation](https://github.com/chanzuckerberg/single-cell-curation/issues) repo and labeled as `deletion`. The issue must be reviewed and approved by @jahilton, and then manually executed by the on-call engineer.

**Comment by danieljhegeman** [comment]
@brianraymor for consideration: what would you think about simply restricting deletes of published data to _super curators_? Then, @jahilton , Jenny, Jim, CZI engineers, etc. can continue to use the Discover API to delete published data -- it would allow Lattice to continue to operate more independently. 

My understanding was that the 'accidental deletion' problems were arising from mistakes by non-Lattice team members.

Happy to continue with the plan as it is laid out in the description above, but just wanted to float this as an option.

**Comment by jahilton** [comment]
>My understanding was that the 'accidental deletion' problems were arising from mistakes by non-Lattice team members.

Nope, it was us. A more formal process with more eyes/hands involved will be great.
