### ISSUE TITLE
Demo schema for RNA-seq atlas is frozen for implementation

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#321]
[Demo Schema](https://docs.google.com/document/d/13ieKBPdFE0lJ9yuVkZoOmy3Hx1Ut-3tFuqAeXdAeAPw/edit#). Currently contains:
* RNA Schema
* Multi-modal Schema (RNA + Protein)

**Comment by ambrosejcarr** [comment]
@jahilton @brianraymor @jychien The RNA schema is ready for review. The protein schema has a few open questions. I'd appreciate if you could flag any high level issues you see with it. 

Please review by Aug 12, or let me know if you need more time.

**Comment by ambrosejcarr** [comment]
Thank you all for your comments. I believe I've addressed the questions that were raised and that we are clear for implementation of the first RNA demo atlas: 
1. We will use the data that are available when Bruce gets started (schema 2.0.0) and are aware that all public facing data will need to be migrated when we move to 3.0.0
2. We will consider adding batch_condition but it is not required for the first demo atlas.
3. We will consider adding secondary data, but it is not required for the first demo atlas.

Conversations about protein data are ongoing.

**Comment by pablo-gar** [comment]
We have landed on a schema for the Cell-Census schema supported by SOMA encodings

Doc is here

https://docs.google.com/document/d/1GKndzCk9q_1SdYOq3BeCxWgp-o2NSQkEmSBaBPKnNI8/edit

The schema will be deposited into https://github.com/chanzuckerberg/cell-census
