### ISSUE TITLE
Test the Seurat artifacts after the 3.0.0 transition

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell#338]

**Comment by brianraymor** [comment]
Is this a manual test? How does this differ from [Need test suite to ensure that dataset rds format conversions are valid](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/939).

**Comment by ebezzi** [comment]
> Is this a manual test? How does this differ from [Need test suite to ensure that dataset rds format conversions are valid](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/939).

It's basically the same thing, but it doesn't look like that ticket ended up in any kind of implementation. Anyway we don't need anything fancy, just a basic notebook that checks if the RDS file can be opened and the fields are in the right place.

**Comment by ebezzi** [comment]
A [script](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/scripts/validate_rds.R) has been added in the portal `scripts` folder that can be used for a very basic QA. Jenny is also helping QAing the RDS artifacts that were uploaded in rdev.
