### ISSUE TITLE
Decide if and how to incorporate secondary metadata

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#341]
Secondary views of cells: Cellxgene's data corpus has "primary" and "secondary" versions of cells. This occurs when meta-analyses re-analyze data, usually with the intent of devising refined annotations. The impact of this is that our corpus may contain secondary versions of primary observations which disagree about metadata annotations. The above use case explicitly generates disagreements at the level of the cell type annotation, but we do not check to ensure that other annotations are in agreement. 

There are reasons for us to expose secondary metadata - when there are multiple metadata they reflect disagreements between experts about the annotations, and resolving these disagreements are key steps towards formulating an authoritative reference of cells. 

Potential Implications: 
obs metadata may take on multiple values from multiple datasets.

See also [comment thread](https://docs.google.com/document/d/13ieKBPdFE0lJ9yuVkZoOmy3Hx1Ut-3tFuqAeXdAeAPw/edit?disco=AAAAeH-N_xc) for original discussion.

**Comment by jahilton** [comment]
>There are reasons for us to expose secondary metadata 

Big caveat that we would be able to map the primary cell to each of its corresponding secondary cells. We have existing cases if we wanted to test that possibility.

**Comment by pablo-gar** [comment]
We have decided not to include this for the Cell Census MVP, it is not requirement for a technical demonstration of SOMA and the Cell Census.

However all h5ads used to create any given census releases are going to be copied into a public S3 bucket that is encoded in the cell census. Thus non-standardized metadata will be available in this form

**Comment by pablo-gar** [comment]
We have decided not to include this for the Cell Census MVP, it is not requirement for a technical demonstration of SOMA and the Cell Census.

However all h5ads used to create any given census releases are going to be copied into a public S3 bucket that is encoded in the cell census. Thus non-standardized metadata will be available in this form
