### ISSUE TITLE
Decide if and how to incorporate batch condition

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#342]
**Batch Condition as a new obs column:** Batch condition is an important metadata used to declare a source of potential technical variation that should be removed when integrating data. However, It is constructed to reference columns in obs, and those columns are not required to be schema columns. 

Non-schematized columns may be included in a json blob, but users would need to extract that information in order to make use of batch_condition in its current form.

A way batch condition could be defined in SOMA would be to assign a numeric value for each combination of (dataset, batch_condition). The user would know that a batch is distinct because it would have a distinct integer, but not be able to understand the provenance.

**Comment by pablo-gar** [comment]
batch condition is not included in the schema for the Cell Census MVP

**Comment by pablo-gar** [comment]
Similarly non-schematized metadata is not included
