### ISSUE TITLE
Ensure accessing cellxgene via mobile devices understand that we recommend using our applications on Desktop.

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#347]
We are increasingly marketing cellxgene through channels that result in discovery of our applications on mobile form factors. 8% of entrants to cellxgene now arrive on mobile or tablet devices. However, our tools are built for desktop consumption. 

Requirement: Users who discover cellxgene through mobile or tablet devices understand that cellxgene is built for desktop use.

Design notes from discussions on slack:
* [Use of user agent to detect device types is discouraged](https://mozilla.github.io/standards-positions/#ua-client-hints)
* [Media queries to detect window widths MAY be a useful direction.](https://kinsta.com/blog/javascript-media-query/#option-3-use-the-matchmedia-api)

References:
* https://czi-sci.slack.com/archives/C02450L5YAX/p1664230703439709
* https://czi-sci.slack.com/archives/C023Q1APASK/p1664316547693339

**Comment by brianraymor** [comment]
@niknak33 - should this be merged into #4451 and then closed?
