### ISSUE TITLE
Organize API handlers, wmg, gene_info, curation, and portal

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell#350]

**Comment by Bento007** [comment]
As part of this work can we also try to tease out the common code between curation and portal API handlers?

**Comment by danieljhegeman** [comment]
@Bento007 did we intend to have me reorganize / standardize the API naming convention in Explorer as well? If not, then I can move this issue from single-cell to single-cell-data-portal. Otherwise I will create one for both single-cell-explorer and single-cell-data-portal.
