### ISSUE TITLE
JSON logging across data portal and explorer

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell#352]
We are already logging to cloudwatch in JSON format in the data portal API server. We should update the remains services to also log in JSON format.

# single-cell-data-portal
- backend/corpora/upload_failures/app.py
- backend/corpora/upload_success/app.py
- backend/corpora/dataset_submissions/app.py
- backend/corpora/dataset_processing/logger.py
- backend/wmg/data/cube_pipeline.py

# single-cell-explorer
- /single-cell-explorer/server/app/app.py

#Definition of Done
- All of the above apps or pipelines produce logs in JSON format

**Comment by metakuni** [comment]
Excluding from 2022Q4 scope as discussed at OKR confidence scoring meeting moving to on-call backlog as future work

**Comment by atolopko-czi** [comment]
- [ ] Issue needs to specify the JSON format/fields to use for pipeline logging.

**Comment by atolopko-czi** [comment]
Would also be useful if API responses log messages included the original request's url and method.

**Comment by metakuni** [comment]
See also https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/540 (duplicate)

**Comment by Bento007** [comment]
This work is complete
