### ISSUE TITLE
Determine paradigm for automated / easy checks for updates

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell#357]
- Investigate existing tooling to solve this problem
- Put forward candidate(s) for on-call workflow to execute the chosen strategy

**Comment by metakuni** [comment]
We just discovered this existing doc:
- https://github.com/chanzuckerberg/single-cell/blob/main/how-we-work/how-to-upgrade-dependencies.md

which should be reviewed and refined as required.

**Comment by danieljhegeman** [comment]
Not a priority.
