### ISSUE TITLE
Biological Consumers can select Cell Census v1 as basis data for Gene Expression

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#362]
**Background**:

Please see the following doc for more context on our [2023 Single Cell Plan](https://docs.google.com/document/d/1mq6LB_mU5rlhH5xHvu_2jUZ6wxdCwrwwNi_lBaw5JnM/edit#heading=h.603dkksh7saq)

H1 2023 Milestone - v1.0 can be selected as basis data for Gene Expression. 

Please ensure that this epic includes versioning for future versions as well.

**Dependencies:**

Blocked on the work that will need to completed by [https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/361](url) - in particular Cell Census API

**Comment by niknak33** [comment]
**Background**:

Please see the following doc for more context on our [2023 Single Cell Plan](https://docs.google.com/document/d/1mq6LB_mU5rlhH5xHvu_2jUZ6wxdCwrwwNi_lBaw5JnM/edit#heading=h.603dkksh7saq)

H1 2023 Milestone - v1.0 can be selected as basis data for Gene Expression. v1.0 Gene Expression summarized data (cell types, gene expression) can be downloaded by users. (Explorer support is not required)

**Dependencies:**

Blocked on the work that will need to completed by [https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/361](url) - in particular Cell Census API

**Comment by dsadgat** [comment]
Due to the complexity of reproducibility and the requirements we might need to refine, we are removing this requirement for the half.
