### ISSUE TITLE
Biological Consumers can select Cell Census v1 and v2 as basis data for Gene Expression

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#364]

**Comment by dsadgat** [comment]
I'm going to close this issue for 2 reasons
1) i believe V2 is not going to be necessary until the end of the year and we are focusing only on H1 right now
2) Once we complete the sister ticket to allow v1, v2 should actually implicitly be allowed. So really its preferrable just to allow versioning in general, which is what the aim for the other epic will address
