### ISSUE TITLE
Increase the velocity of dataset schema evolution and dataset migration

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#365]
# Goal Alignment

**H2 Goal 2: The quality of CZ Census metadata is improved.**

---

# Technical Design

[Tech Spec: Increase the velocity of dataset schema evolution and dataset migration](https://docs.google.com/document/d/1QNWicEb_C7W5B-L6Lb9jbnX897nUnoamEdaebznB_jw/edit#heading=h.jcf27gbiblyg). 

---

## Aspiration

This is the next step for **Discover tooling is upgraded so that data submitters have access to up-to-date annotations, Data integrators have access to key fields for data integration, and it is easier for curators to execute data migrations**.

_Ontology-only updates and migrations must be performed on a frequent cadence (monthly) with limited curator intervention and **without the requirement to always download and upload** revised datasets._  This implicitly means that the upload of a dataset should not be the only trigger for the validation and conversion steps in the ingestion pipeline. 

As @ambrosejcarr recently wrote:

> Curation and migration ensure that the datasets we host retain their value longer ... by ensuring that datasets have annotations that reflect the most up to date thought on biological concepts and enable the data to be used, compared, and integrated more seamlessly.

---

# Conceptual Workflow for Migrations

This will build on the _dry run_ and _curator scripting_ model created in [Increase the velocity of ontology-only dataset schema updates and dataset migration](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/441)

## Ordering of Operations

When refinements are made to existing metadata fields, there may be cases where multiple fields are impacted and operations must be ordered. During schema 4.0.0 migration:
1. The new `tissue_type` field is annotated by detecting the `" (organoid)"` or `" (cell culture)"` suffix for `tissue_ontology_term_id`. 
1. Then, that suffix must be removed from `tissue_ontology_term_id`. 
1. Then, validation can occur.
1. `tissue` is corrected when its label is re-applied.

## _dry-run_

A _dry-run_ is performed to assess the **impact** from schema field changes and to collect guidance from Lattice for cases requiring curator intervention prior to updating datasets.

## Automate Updates to Ontologies and Gene References

**Note**: Refined and addressed in [Increase the velocity of ontology-only dataset schema updates and dataset migration](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/441). 

---

## Add Metadata field

Metadata fields may be added. **It must be possible for curators to script annotations for added metadata fields that _curators MUST annotate_.** 

The following metadata fields are added in schema 4.0.0, but **DO NOT** require curator intervention:

* [`citation`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#citation) is a known value.
* [`feature_length`](https://github.com/chanzuckerberg/single-cell-curation/issues/516) is calculated.
* [`observation_joinid`](https://github.com/chanzuckerberg/single-cell-curation/issues/523) is calculated.
* [`schema_reference`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#schema_reference) is a known value.
* [`tissue_type`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#tissue_type) is a known value.

**Note**: `tissue_type` is the only addition that _curators MUST annotate_ for new datasets. 

Nonetheless, the design must support future automation.

IF ALL or MOST values for an added metadata field that _curators MUST annotate_ cannot be automatically annotated during migration, then this is communicated to curators during the schema design rather than reporting during the _dry-run_.  A previous example in schema 3.0.0 was [`donor_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#donor_id).

IF SOME values for an added metadata field that _curators MUST annotate_ cannot be automatically annotated, THEN _document_ the following in curator report:

* collection id: dataset id
* **field name** cannot be annotated
* requires curator intervention

A previous example in schema 3.0.0 was [`suspension_type`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#suspension_type). 

---

## Update Metadata field requirements

Metadata fields may have updated requirements that introduce fresh failures. Updates may include stricter requirements, changes to the format, or changes to the type. 

**It must be possible for curators to script annotations for metadata fields with updated requirements _that curators MUST annotate._**

The following metadata fields that _curators MUST annotate_ have updated requirements in schema 4.0.0:

 * [`cell_type_ontology_term_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#cell_type_ontology_term_id)
 * [`self_reported_ethnicity_ontology_term_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#self_reported_ethnicity_ontology_term_id)
 * [`tissue_ontology_term_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#tissue_ontology_term_id)

A previous example in schema 3.0.0 was:

  * [Update guidance in `assay_ontology_term_id` for annotating missing terms in EFO](https://github.com/chanzuckerberg/single-cell-curation/issues/190#issuecomment-1057086092)

For historical reasons, there are three cases where curated fields exist in many datasets that were neither documented in the schema nor fully validated by `cellxgene-schema` CLI:

* In schema 4.0.0, [`{column}_colors`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#column_colors) is added. It is consumed in CELLxGENE Explorer for color assignments. Unfortunately, the quality of its validation has been appalling. Exceptions have been suppressed. Values have been permitted that are then ignored. Please collaborate with @atarashansky on [{column}_colors must be validated](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/513).
* Visium and Slide-Seq experiments have been curated _under current capabilities_ and [will be added to the schema and validated in 2024](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/473).
* [RNA/ATAC and CITE-seq curated _under current capabilities_](https://docs.google.com/document/d/1mnem9U5UZ2CRpuSGQ0JtOVDn05w-4oRs5POwlDFp4bQ/edit#heading=h.nc5agzmeh6t0)

These cases are similar to updating the requirements for an existing metadata field. 

IF an existing value is now invalid and cannot be corrected, THEN _document_ the following in curator report: 
* collection id: dataset id
* **value** is invalid for **field name**
* requires curator intervention

**Note**: `{column}_colors` validation may produce many failures in the _dry-run_ due to stricter validation. Potential failures may include:
1. {column} references a label field instead of a term field. The {column} can be renamed from the label field to the term field if the term field is NOT also present as a {column} which would create a conflict that would require curator intervention.  Per @jahilton - we could also choose to simply delete such offending {column}(s) because no one noticed the issue.
1. The format for the value is RGB and must be converted.

---

## Deprecate Metadata field

Deprecated (deleted) metadata fields must be deleted. There are no cases in schema 4.0.0. Nonetheless, the design must support future automation.

A previous example in schema 3.0.0 was:

* Deprecated `X_normalization`
   
---

## Rename Metadata field

Metadata fields may be renamed. There are no cases in schema 4.0.0. Nonetheless, the design must support future automation.

Previous examples in schema 3.0.0 were:

  * Renamed `ethnicity_ontology_term_id` to `self_reported_ethnicity_ontology_term_id`
  * Renamed `ethnicity` to `self_reported_ethnicity`
 
---

## Warnings from new Anndata versions

See [**#single-cell-four**](https://czi-sci.slack.com/archives/C03PXFMM7ST/p1677019037390099).

Example:

```
2023-02-21 22:15:44 804754  WARNING  /home/bruce/cell-census/venv/lib/python3.9/site-packages/anndata/compat/__init__.py:263: FutureWarning: During AnnData slicing, found matrix at .uns['neighbors_hm']['connectivities'] that happens to be dimensioned at n_obs×n_obs (4329×4329).

These matrices should now be stored in the .obsp attribute.
This slicing behavior will be removed in anndata 0.8.
```

IF warnings occur, THEN document the following in the curator report:

* collection id: dataset id
* warning from AnnData

More needs to be understood about warnings before an automated solution can be proposed.

---

## Automate preprint DOI to published DOI updates

[Update the DOI in the A single-cell transcriptional roadmap of the mouse and human lymph node lymphatic vasculature collection](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/106) is an example of an updated DOI that was discovered during prototyping. If an existing preprint  DOI is queried again AND it has been published since the previous query, then Crossref returns the published DOI in:

```
if is_preprint:
    try:
        published_doi = message['relation']['is-preprint-of']
       # the new DOI to query for ...
        if published_doi[0]['id-type'] == 'doi' :
            display(published_doi[0]['id'])
    except KeyError:
        pass
```

This would allow the portal to refresh preprint DOI(s) with their published DOI(s) on a regular cadence. 

Lattice discovered a case in the past where the publishers failed to update the relationship between a [preprint DOI](https://api.crossref.org/works/10.1101/2020.04.03.024075) and its [publication DOI](https://api.crossref.org/works/10.1038/s41586-020-2797-4). 

---

## Automate Dataset Title updates

This automation is **out of scope** for this iteration. 

~~This feature has been [requested in the past](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/145).~~

~~There have also been conversations in [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1658186241086299) about better naming guidelines that might require an editorial pass on dataset titles in the future.~~

---

## Inspiration

@jahilton shared _[Opportunities to optimize](https://docs.google.com/document/d/1oRvxt88-jP3hAfMB2K3CGOob_Cg43Q5Q6LcEjK538Zw/edit#heading=h.vn1n18w5yuv4)_ based on the Lattice experience with the recent 3.0.0 migration. 

Earlier blue-skying on [Validation/Submission strategy (aka Automating Migration)](https://docs.google.com/document/d/1zFQsFiRSMbXikWk5INzcvIBL2zDzYEs4cZ21rVMgpEw/edit#heading=h.bp2i01ag6tb)

Review [LinkML](https://linkml.io/)

**Comment by metakuni** [comment]
Updated epic as:
* start: 2023-08-28
* end: 2023-11-17
 
The end date will be further refined after the schema 4 tech spec, epics/issues and estimates are refreshed by @nayib-jose-gloria in the week of 2023-09-11.

**Comment by metakuni** [comment]
Schema 4 migration completion moved to 2023-12-01 based on project re-estimation and extension of CI/CD work.
