### ISSUE TITLE
Delete unused S3 prod buckets

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell#372]
See list of buckets to delete [here](https://docs.google.com/document/d/15JqTV-nd73lthNyHKcr4u0iaeGAiJBLW9tBmeu3L0lk/edit).

For buckets that are remaining, document their usage in [Tech Overview](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.415jrraq75id).

**Comment by metakuni** [comment]
Issue moved to [chanzuckerberg/single-cell-infra #807](https://github.com/chanzuckerberg/single-cell-infra/issues/807) via [**Zenhub**](https://www.zenhub.com/)
