### ISSUE TITLE
Ingest 5M high priority primary cells

### ISSUE THREAD

**Issue by 99norbs** [chanzuckerberg/single-cell#376]
Outcome 1: Increase the scope and comprehensiveness of CELLxGENE Discover data corpus by curating datasets from HCA Bionetworks and funded networks reaching 40 million cells
- Milestone 1: Increase data corpus by 5 M high-priority primary cells per half (end of Q1)

Dependency: Milestone 2: Identify and ingest ?% of bionetworks datasets required for atlas integration → reflect dependency on Annotate (end of Q1)

**Comment by brianraymor** [comment]
@BAevermann @maniarathi - can this be closed?

**Comment by BAevermann** [comment]
Outcome met! A bit a go ...
