### ISSUE TITLE
Ingest datasets identified by the bionetworks as required for atlas integration

### ISSUE THREAD

**Issue by norbid** [chanzuckerberg/single-cell#378]
Outcome 1: Increase the scope and comprehensiveness of CELLxGENE Discover data corpus by curating datasets from HCA Bionetworks and funded networks reaching 40 million cells
Milestone 1: Identify and ingest ?% of bionetworks datasets required for atlas integration → reflect dependency on Annotate (end of Q1)

**Comment by BAevermann** [comment]
Superceded by more granular epics
