### ISSUE TITLE
Updated data trackers & roadmaps

### ISSUE THREAD

**Issue by norbid** [chanzuckerberg/single-cell#379]
Outcome 2: Implement data prioritization policy based on metric(s) that scientists can intuitively understand reflect comprehensiveness of the data and the implicit strategy to arrive at relative completeness
Milestone 1: Establish data trackers and update data roadmap to reflect new networks
Milestone 2: Define/socialize high level metric(s) to guide data acquisition strategy
Milestone 3: Define data driven metric using either biological knowledge or purely empirical modeling (stretch)

**Comment by BAevermann** [comment]
Duplicate. Work complete.
