### ISSUE TITLE
Scientists using hosted cellxgene can calculate differential expression on populations of cells with arbitrary size

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#38]
_**As a scientist, I want to be able to calculate differential expression between two groups of cells of any size so that I can identify the genes that uniquely characterize a given type of cells.**_

REQ: Hosted differential expression takes approximately the same amount of time as desktop differential expression (plus some small overhead that is a function of the size of a dataset).

**Comment by MDunitz** [comment]
How long does this currently take on the desktop? Is it cell count dependent?

**Comment by bmccandless** [comment]
> How long does this currently take on the desktop? Is it cell count dependent?

It's actually h5ad which is faster, which is what most people would run on the desktop.  It's faster because it is all in memory, and therefore can be 100x faster that the current tiledb implementation, which has to read much of the matrix in from s3 before doing the computation.   It is cell count and gene count dependent, also sparse vs dense dependent.

**Comment by mckinsel** [comment]
Surely not _any_ size, right? Hard to come up with acceptance criterion for that.

**Comment by tihuan** [comment]
@bmccandless please link the design ticket as a blocker!

And decide on the max size - 

The ask is that whoever uses desktop cellxgene needs to find hosted cellxgene has compatible performance to convince them to use hosted cellxgene

What's the performance goal?

>>> Workshop

@maniarathi

**Comment by signechambers1** [comment]
@bmccandless would you mind linking the design doc ticket as a blocker? I'd like to add to the product backlog so we can prioritize next sprint!

**Comment by ambrosejcarr** [comment]
Duplicate of chanzuckerberg/single-cell-explorer#212
