### ISSUE TITLE
Decide how we will refer to the concatenated data object (team working name: Cell Census)

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#382]
**Person Accountable:** Tiffany
**Timeline:** TBD

**Straw-person approach (Tiffany to refine):** 
1. Align on how Single Cell wants to describe the experience. Critically, is the "concatenated data object" part of CZ CELLxGENE Discover or something that needs to be separately branded?
2. Description + Candidate names to seed name generation. includes interested CZI team members outside of SCB. 
3. Names ranked by key stakeholders
4. Short-list sent to legal for vetting
5. Decision on legally vetted names (who decides?)

**Open questions:** 
1. Are 4 & 5 needed if the "concatenated data object" is part of CZ CELLxGENE Discover?

**See Also:**
* [Onboarding context for CZI Science team members](https://docs.google.com/document/d/1wVgWcOJT_FzOj-b0Zt8K4CvePgBuCeoKAFHl1WzICco/edit)

**Comment by pablo-gar** [comment]
Official final decision:

Product: CZ CELLxGENE Discover
Feature: Census
Full name: CZ CELLxGENE Discover Census
Python package: `cellxgene-census`
Github repo: `cellxgene-census`
R package: `cellxgene.census`
