### ISSUE TITLE
Update field name names [term_id] in schema specification

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#40]
@mckinsel wrote:
schema fields were renamed, see [discussion](https://github.com/chanzuckerberg/corpora-data-portal/pull/460#discussion_r456798892)

> The ontology_term_id fields may be empty strings when no appropriate ontology value is available, for example if the cell_type field describes a cell type for which not ontology term exists or if the ethnicity is unknown.

**Comment by maniarathi** [comment]
This can be closed since the Markdown is the authoritative source of the Corpora schema.

**Comment by brianraymor** [comment]
I cannot find a schema design document in the RFC folder. Re-opening until we can locate and validate.

**Comment by brianraymor** [comment]
The schema markdown now lives in the [data portal](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/backend/schema/corpora_schema.md). It has been updated.

@mckinsel added a deprecation note and link to the original google doc.
