### ISSUE TITLE
Update licenses for 2023

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell#403]
Happy New Year! 🎆  🍾 

Update licenses for 2023:

- [x] https://github.com/chanzuckerberg/cellxgene/blob/main/LICENSE.txt
- [x] https://github.com/chanzuckerberg/single-cell/blob/main/LICENSE
- [x] https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/LICENSE
- [x] https://github.com/chanzuckerberg/single-cell-curation/blob/main/LICENSE.txt
- [x] https://github.com/chanzuckerberg/single-cell-explorer/blob/main/LICENSE.txt
- [x] https://github.com/chanzuckerberg/cell-census/blob/main/LICENSE
- [x] https://github.com/chanzuckerberg/single-cell-annotation/blob/main/LICENSE

**Comment by atolopko-czi** [comment]
@maniarathi Does this entail anything beyond updating the end year in these files?
* https://github.com/chanzuckerberg/single-cell/blob/main/LICENSE
* https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/LICENSE
* https://github.com/chanzuckerberg/single-cell-curation/blob/main/LICENSE.txt
* https://github.com/chanzuckerberg/single-cell-explorer/blob/main/LICENSE.txt
* https://github.com/chanzuckerberg/cell-census/blob/main/LICENSE

**Comment by maniarathi** [comment]
Nope, that's it. 

Also the following:
https://github.com/chanzuckerberg/cellxgene/blob/main/LICENSE.txt
https://github.com/chanzuckerberg/single-cell-annotation/blob/main/LICENSE
