### ISSUE TITLE
Develop pipelines for demonstration projects

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#406]
**Milestones:**
By Jan 31st, establish recurring meetings across the CZI efforts to support funding, building and doing demonstration projects. 
By Feb 15th, clarify major themes among possible demonstration projects and build out a tracker of potential projects. Populate it with >15 project ideas, prioritize based on effort, risk and value, and initiate discussions with >10. 
By March 15, develop 3-5 projects to the stage of having a clear project plan that clarifies timelines and resourcing needs. 
By  April 15, identify 2-3 projects that are maturing rapidly and may be candidates for incorporation into or references for initial submission and publication in H2 

[Additional Context.](https://docs.google.com/document/d/1dRbqLq4mWf7ljct_iTYvpJoX6ZhCdUvu5x7R4_aHj5U/edit#)

**Comment by maniarathi** [comment]
Resolving per offline conversation with Jonah.
