### ISSUE TITLE
Investigate methods to report on unique downloads of matrices

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#43]
Per the August 27 refinement

@mweiden wrote:

1. Here is UCSC's exporter https://github.com/HumanCellAtlas/google-analytics-exporter It's an option, not required usage.
2. @mckinsel suggested using a query on s3 data access logs (perhaps via CloudWatchLogs Insights)

Solution will need to be validated with *Trust*.

**Comment by maniarathi** [comment]
I investigated querying S3 data logs and was able to figure out the number of times each dataset was downloaded as well as whether the download was from the browser or via curl. This is a very low cost solution so I will enable logs on our S3 bucket and document the queries to figure out the above statistics.
