### ISSUE TITLE
Increase the velocity of ontology-only dataset schema updates and dataset migration

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#441]
## Goal Alignment

**H2 Goal 2: The quality of CZ Census metadata is improved.**

---

## Technical Design

[Tech Spec: Increase the velocity of dataset schema evolution and dataset migration](https://docs.google.com/document/d/1QNWicEb_C7W5B-L6Lb9jbnX897nUnoamEdaebznB_jw/edit#heading=h.jcf27gbiblyg). 

---

## Aspiration

This is the next step for **Discover tooling is upgraded so that data submitters have access to up-to-date annotations, Data integrators have access to key fields for data integration, and it is easier for curators to execute data migrations**.

_Ontology-only updates and migrations must be performed on a frequent cadence (monthly) with limited curator intervention and **without the requirement to always download and upload** revised datasets._  This implicitly means that the upload of a dataset should not be the only trigger for the validation and conversion steps in the ingestion pipeline. 

As @ambrosejcarr recently wrote:

> Curation and migration ensure that the datasets we host retain their value longer ... by ensuring that datasets have annotations that reflect the most up to date thought on biological concepts and enable the data to be used, compared, and integrated more seamlessly.

The dataset schema must be responsive to emerging requirements from the the Cell Census (cell and tissue mappings). 

---

### How ontologies annotate deprecation and replacements

**Important Note**: Tthe [`tissue_ontology_term_id`](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#tissue_ontology_term_id) MAY use either UBERON or CL ontologies.  

Most of the ontologies are updated on a ~monthly cadence. For example - see [CL releases](https://github.com/obophenotype/cell-ontology/releases).

 There are three ways that ontologies annotate deprecation of terms and their potential replacements:

1. **[obo.IAO_0100001 (replaced by)](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0100001)** _Use on obsolete terms, relating the term to another term that can be used as a substitute_. (Also see https://github.com/information-artifact-ontology/ontology-metadata/issues/58). 

**IMPORTANT NOTE**: The format for the value of **obo:IAO_0100001** varies and may need to be normalized:
* http://purl.obolibrary.org/obo/CL_1000147
* obo.CL_1000147
* CL:1000147

    **Sample:**

```
    <!-- http://purl.obolibrary.org/obo/CL_0000663 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/CL_0000663">
        <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/CL_1000147"/>
        <rdfs:comment>https://github.com/obophenotype/cell-ontology/issues/726</rdfs:comment>
        <rdfs:label>obsolete valve cell</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
```

**Important Note**: It MAY recommend term replacements from other unsupported ontologies (PCL in the example below):

```
    <!-- http://purl.obolibrary.org/obo/CL_4023078 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/CL_4023078">
        <obo:IAO_0000115>OBSOLETE A L2/3 pvalb-like sst GABAergic cortical interneuron (Mus musculus) that has basket morphology.</obo:IAO_0000115>
        <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/PCL_1000003"/>
        <terms:contributor rdf:resource="https://orcid.org/0000-0001-7258-9596"/>
        <oboInOwl:hasExactSynonym>basket L2/3 PV-like SST (Mus)</oboInOwl:hasExactSynonym>
        <rdfs:comment>Moved to PCL - see https://github.com/obophenotype/brain_data_standards_ontologies/issues/231. Use PCL:1000003 instead.</rdfs:comment>
        <rdfs:label>obsolete basket morphology L2/3 pvalb-like sst GABAergic cortical interneuron (Mus musculus)</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/CL_4023078"/>
        <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000115"/>
        <owl:annotatedTarget>OBSOLETE A L2/3 pvalb-like sst GABAergic cortical interneuron (Mus musculus) that has basket morphology.</owl:annotatedTarget>
        <oboInOwl:hasDbXref>PMID:33184512</oboInOwl:hasDbXref>
    </owl:Axiom>
```

2. **[consider](https://raw.githubusercontent.com/geneontology/go-ontology/master/contrib/oboInOwl#consider)** _Gives a term which may be an appropriate substitute for an obsolete term, but needs to be looked at carefully by a human expert before the replacement is done_.

    **Sample:**

```
    <!-- http://purl.obolibrary.org/obo/CL_0000224 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/CL_0000224">
        <obo:IAO_0000115>OBSOLETE: A classification of cells by the number of their nuclei.</obo:IAO_0000115>
        <oboInOwl:consider>CL:0000000</oboInOwl:consider>
        <oboInOwl:consider>CL:0000003</oboInOwl:consider>
        <oboInOwl:consider>CL:0001034</oboInOwl:consider>
        <rdfs:comment>This term was made obsolete because there is no difference in meaning between it and &apos;cell&apos;, as any cell can be classified by its nuclear number (note that this term was previously used as a parent class of enucleate cell). If you have used this term in annotation, please replace it with cell (CL:0000000), native cell (CL:0000003), or cell in vitro (CL:0001034) as appropriate.</rdfs:comment>
        <rdfs:label>obsolete cell by nuclear number</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/CL_0000224"/>
        <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000115"/>
        <owl:annotatedTarget>OBSOLETE: A classification of cells by the number of their nuclei.</owl:annotatedTarget>
        <oboInOwl:hasDbXref>FB:ma</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>GOC:tfm</oboInOwl:hasDbXref>
    </owl:Axiom>
```
    
3. No annotation but suggestions in the **comment**.

    **Sample**

    

```
    <owl:Class rdf:about="http://purl.obolibrary.org/obo/CL_0008029">
        <terms:contributor rdf:resource="https://orcid.org/0000-0002-7073-9172"/>
        <oboInOwl:creation_date rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2017-07-12T11:10:52Z</oboInOwl:creation_date>
        <rdfs:comment>See https://github.com/obophenotype/cell-ontology/issues/1540. Consider GABAergic neuron or inhibitory interneuron instead. Do note that not all GABAergic neurons are inhibitory (see PMID:12209121) and replacing inhibitory neuron with GABAergic neuron should be done with caution.</rdfs:comment>
        <rdfs:label>obsolete inhibitory neuron</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
```

### _dry-run_

A _dry-run_ is performed to assess the **impact** from pending ontology updates and to collect guidance from Lattice for cases requiring curator intervention prior to updating datasets.

Discover API queries can identify the `set` of unique term identifiers present in the data corpus for a specific ontology such as CL:

```
{'CL:0000000',
 'CL:0000001',
 'CL:0000003',
 'CL:0000006',
 'CL:0000010',
 'CL:0000015',
 'CL:0000019',
 'CL:0000021',
 ...
```

Each term should also reference the id for its collection and dataset for the curator report.

The set of terms in the data corpus are then compared against the set of `deprecated` terms in the latest version of the corresponding ontology. 

IF annotated with **obo.IAO_0100001 (replaced by)** AND IF the replacement term is from the required ontology or ontologies, THEN _document_ the following in the curator report:

* collection id: dataset id
* obsolete term identifier
* **replaced by** and value
* **comment** and value
* **term tracker** and value 

This case may be automated during migration.

IF annotated with **obo.IAO_0100001 (replaced by)** AND IF the replacement term is from an ontology that does not match the required ontology or ontologies, THEN document the following in the curator report:

* collection id: dataset id
* obsolete term identifier
* **replaced by** and value
* **comment** and value
* **term tracker** and value 
* requires curator intervention

This case must be scripted during migration.

IF annotated with **consider**, THEN document the following in the curator report:
* collection id: dataset id
* obsolete term identifier
* **consider** and value
* **comment** and value
* **term tracker** and value 
* requires curator intervention

This case must be scripted during migration.

IF NOT annotated with either  **obo.IAO_0100001 (replaced by)**  or **consider**, THEN document the following in the curator report:
* collection id: dataset id
* obsolete term identifier
* **comment** and value
* **term tracker** and value 
* requires curator intervention

This case must be scripted during migration.

IF a revision is pending for a collection THEN document the following in the curator report:
* revision in progress
* collection id
* requires curator intervention

Review the curator report with Lattice for guidance on cases that require curator intervention. For example, if there were three options for a **consider** annotation, Lattice may prefer only one option. 

With this information, all revisions can be automated and/or scripted in one migration pass. 

Also see [cellxgene-schema must ensure that ontology terms are not obsolete](https://github.com/chanzuckerberg/single-cell-curation/issues/119) for a prototype to detect obsolete terms and recommend replacement terms. 

---

## Automate Post-Ontology Updates

The dataset schema states:

> The most accurate ontology term MUST always be used. If an exact or approximate ontology term is not available, a new term may be requested ...

Lattice tracks new term requests and their outcomes. If a requested term is added to an ontology release, then a work item is added to an issue such as [post-ontology bump updates (3.0.0+1)](https://github.com/chanzuckerberg/single-cell-curation/issues/373). 

Update _Ontology Term 1_ to _Ontology Term 2_ for `Dataset id` in `Collection id` must be scripted during the migration. 

---

## Updates to `cellxgene-schema` CLI for ontologies

Currently, `cellxgene-schema` ontology processing [only captures](https://github.com/chanzuckerberg/single-cell-curation/blob/79a78b41414441d6f79ecf57baa57e3cea0c5eb3/cellxgene_schema_cli/scripts/ontology_processing.py#L145) that a term is deprecated. This must be extended to include the following when available:
* **obo.IAO_0100001 (replaced by)**
* **consider**
* **comment**
* **obo:IAO_0000233 (term tracker)**

When a `deprecated` term is detected during validation, the following must occur:

IF annotated with **obo.IAO_0100001 (replaced by)** AND IF the replacement term is from the required ontology or ontologies, THEN:
* Print warning message such as "`term` is deprecated and replaced by `replacement term`."
* Fail validation

IF annotated with **obo.IAO_0100001 (replaced by)** AND IF the replacement term is from an ontology that does not match the required ontology or ontologies, THEN:
* Print warning message such as "`term` is deprecated and replaced by `replacement term` from an unsupported ontology."
* Fail validation

IF annotated with **consider**, THEN:
* Print warning message such as "`term` is deprecated. Consider the following replacements: `consider`."
* Fail validation

IF NOT annotated with either  **obo.IAO_0100001 (replaced by)**  or **consider**, THEN:
* Print warning message such as "`term` is deprecated with no recommended replacement. Review comment: `Comment`."
* Fail validation

## Automate Updates to Gene References

Gene references are not updated as often as the ontologies. 

### _dry-run_

- Refresh (download and process) pinned gene references

For each dataset in the collection, if a gene is deprecated, THEN document the following in the curator report:
* collection id: dataset id
* total genes in dataset
* list of obsolete genes to be filtered out

### During migration:
- Apply _Lattice algorithm_ as described by @jahilton:
> Our curation practices have not been to "convert Ensembl ids" so I feel this would deviate from practices up til now. Instead, we just filter out features that aren't represented by an Ensembl id that is present in the pinned annotation.

In case it's helpful, our standard procedure for filtering out deprecated genes - adapted from our [notebook w/ sample curation code](https://github.com/Lattice-Data/lattice-tools/blob/main/cellxgene_resources/curation_sample_code.ipynb)...
```
ref_files = [
    'genes_ercc.csv',
    'genes_homo_sapiens.csv',
    'genes_mus_musculus.csv',
    'genes_sars_cov_2.csv'
]

if not os.path.exists('genes_approved.csv'):
    ids = pd.DataFrame()
    for f in ref_files:
        df = pd.read_csv(f, names=['feature_id','symb','num','length'],dtype='str',index_col=False)
        ids = ids.append(df)
        os.remove(f)
    ids.to_csv('genes_approved.csv', index=False)

approved = pd.read_csv('genes_approved.csv',dtype='str')
```
```
var_to_keep = adata.var.index.tolist()
var_in_approved = adata.var.index[adata.var.index.isin(approved['feature_id'])].tolist()
var_to_keep = [e for e in var_to_keep if e in var_in_approved]
adata = adata[:, var_to_keep]
```
---

## Updates and Private Collections

1. The UUIDs for private collections and their datasets MUST NOT be exposed to the public in _dry-run_ curator reports. Access to these reports MUST be carefully managed.

1. Publication of private collections with datasets that are not at the schema version required for new submissions MUST be blocked. The `publish` button MUST be disabled. 

1. The UUIDs for private collections and their datasets MUST NOT be exposed by schema migration scripts in `single-cell-curation`.  Therefore, migration of datasets in private collections can only be automated if no curator intervention is required. 

---

## Updates and Private Revisions of Public Collections

1. The UUIDs for private revisions of public collections and their datasets MUST NOT be exposed to the public in _dry-run_ curator reports. Access to these reports MUST be carefully managed. If a revision is in progress, then it MUST be documented in the curator report. (The curator MAY choose to cancel the revision). Automation MUST NOT update the published collection or its private revision. 

1. Publication of private revisions of public collections with datasets that are not at the schema version required for new submissions MUST be blocked. The `publish` button MUST be disabled. 

---

**Comment by metakuni** [comment]
Added placeholder envelope dates of Apr 17 - Jun 30 for this epic so that it's represented on the roadmap. These will be refined as part of the initial discovery work.

cc: @nayib-jose-gloria

**Comment by brianraymor** [comment]
Per conversation with @maniarathi - tracking this as an independent epic for 3.1 although it is an increment towards full automation of schema changes.Removed from its parent epic.

**Comment by metakuni** [comment]
Updated epic end date to 2023-08-25.

The 3.1 migration completion date was moved to this week due to issues encountered during the 1st attempt last week. The migration run was started last night and is on track for completion this week. The Seurat conversion fix is still being tested and will be applied once the migration run is complete.

Impacted teams (Lattice, Census, Gene Expression) have been made aware of the above.
