### ISSUE TITLE
[Discovery] As a Data Consumer, I want ontology modeling to be consistent across CELLxGENE experiences and to be accessible to me to reproduce in my own code.

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#446]
# [Tech Spec](https://docs.google.com/document/d/17Qv_9iJsztjcpu6CMpvbrjh8iJh2vwaSB13azFLBJO8/edit)

# Story

_As a Data Consumer, I want ontology modeling to be consistent across CELLxGENE experiences and to be accessible to me to reproduce in my own code._

# Context

The `cellxgene-schema` CLI [downloads and processes](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/scripts/ontology_processing.py) pinned ontologies to address the schema requirements. 

There is separate (distributed in the code base) ontology processing occurring for _filter by metadata_, _filter with ontology awareness_, _gene expresssion_, _cell guide_, and _cell census_. 

We should investigate integrating all required ontology processing into the ontology preparation step for the `cellxgene-schema` CLI  to eliminate duplication of code and ensure that all features are based on the pinned versions of the ontologies. 

There should be one supported parser (owlready2/pronto) and one supported ontology format (owl/obo). See [OWL, OBO, JSON? Base, simple, full, basic? What should you use, and why?](https://oboacademy.github.io/obook/explanation/owl-format-variants/).

During Discovery, [Proposal: Standardization of ontology-derived process and assets of CELLxGENE Discover](https://docs.google.com/document/d/10rFC55RCOyt8zDO1iBXEap5sVUBRwrBgivSnxqz9spk/edit#heading=h.9jrt25c1j4et) must be finalized.

Also see the @pablo-gar prototype discussed in [#single-cell-data-wrangling](https://czi-sci.slack.com/archives/C024HCSH9PT/p1697232968315399)

[Code](https://gist.github.com/pablo-gar/1b2fc78a91b715256f79a5aa9cbcb00a)
[Notebook](https://colab.research.google.com/drive/1ZnMOL0dfSAMOk8axQIl_6Vq-dIAOHLLs#scrollTo=yDiaGFr1o81z)

---

# Internal _Inventory_

A first step would be to _inventory_ the use of ontologies and ontological artifacts (like the ASCT+B tables in CellGuide).

@atolopko-czi wrote earlier:

_I've attempted to capture the currently ad hoc, manual [Schema Upgrade Process](https://docs.google.com/document/d/1R3a43eLVtWLOxgSu2HCMdD8QK5hddHjtY7uZJrC4VuE/edit). This can serve as requirements for what processes and configuration updates need to be automated and simplified in order to address this story._

@brianraymor adds:

***Trust but verify*** this document during Discovery.

Also see [CellGuide Technical specification](https://docs.google.com/document/d/16xPCK5QQoCHC3_0GjzsBedtzeAfDzKnFFFhZo1WC5VI/edit#).

Also see related thread in [**#single-cell-data-vis**](https://czi-sci.slack.com/archives/C0247APK621/p1678478848628269). 

# Requirements

## Tissue Mapping

See [**single-cell-census**](https://czi-sci.slack.com/archives/C048BN7K6U8/p1667600105942149).

**Definition**: _high-level mapping of a tissue, e.g. “Heart” is the tissue_general of “Heart left ventricle”_

All high-level mappings (1-1 or tree) of tissue MUST be defined. The results will be consumed by all CELLxGENE _experiences_ for consistency.

---

Two tissue mappings are implemented in CELLxGENE Discover:

1. Discover UX Tissue Filter [maps a tissue ](https://github.com/chanzuckerberg/single-cell-data-portal/blob/2505cefa0408cb7b0efd5df75649fbd477fc8fa4/scripts/compute_tissue_and_cell_type_mappings.ipynb)to its _System_ and _Organ_. 
1. Gene Expression maps a tissue to its [_"high-level" tissue_ ](https://github.com/chanzuckerberg/single-cell-data-portal/blob/9b94ccb0a2e0a8f6182b213aa4852c491f6f6aff/backend/wmg/data/tissue_mapper.py). Also see [Available Tissues in Gene Expression](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_4__Available%20Tissues). 
1. Census copied both the Gene Expression model and [code](https://github.com/chanzuckerberg/cellxgene-census/blob/379a8cafda5549c23ace89941ee38e747f18e122/tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/tissue_mapper.py#L22). Both `tissue_general` and `tissue_general_ontology_term_id` are defined in the [census schema](https://github.com/chanzuckerberg/cellxgene-census/blob/main/docs/cellxgene_census_schema.md#cell-metadata--census_objcensus_dataorganismobs--somadataframe). 

@jahilton proposed an ordered list model - 
```
[
  most narrow UBERON term which conceptually maps to curated tissue general / organ,
   ... ,
  most broad UBERON term which conceptually maps to curated system
]
```

## Cell Type Mapping

All high-level mappings (1-1 or tree) of cell types MUST be defined. The results will be consumed by all CELLxGENE _experiences_ for consistency.

---

Known cell type mappings implemented in CELLxGENE Discover:

1. Discover UX Cell Type Filter [maps a cell type ](https://github.com/chanzuckerberg/single-cell-data-portal/blob/2505cefa0408cb7b0efd5df75649fbd477fc8fa4/scripts/compute_tissue_and_cell_type_mappings.ipynb)to its _Cell Class_ and _Cell Subclass_. 

## Development Stages Mapping

# Research

[Common Coordinate Framework ontology ](https://github.com/hubmapconsortium/ccf-ontology)
[ontoProc Ontololgy Interfaces for Bioconductor](https://bioconductor.org/packages/release/bioc/vignettes/ontoProc/inst/doc/ontoProc.html)
[Ontology Access Toolkit](https://incatools.github.io/ontology-access-kit/introduction.html)

The Tissue mappings and the [cellxgene-schema CLI](https://github.com/chanzuckerberg/single-cell-curation/blob/2237d6ab0d8b55eeaaaa0da76ef14a8bb57526b2/cellxgene_schema_cli/scripts/ontology_processing.py#L183) all calculate ancestors and need a common approach. Also see:

* [Reasoning](https://incatools.github.io/ontology-access-kit/guide/relationships-and-graphs.html#graph-traversal-and-relation-graph-reasoning) about [Ancestors](https://incatools.github.io/ontology-access-kit/glossary.html#term-Ancestor) using OAK.

**Comment by metakuni** [comment]
Consider [cellxgene-census#17](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/cellxgene-census/17).

**Comment by metakuni** [comment]
One possible external use case:

@jahilton writes:
> The [scFAIR](https://sc-fair.org/) group would like to provide a table on their site that links out to what studies are in various resources
So they’d like to query CxG Collections (published Collection URL, publication DOI, the ontology IDs in the schema values). _**They may then add on a wrapper that traverses the ontology graphs like the CxG UI filters do.**_

Note that the above has yet to be scoped as a requirement. This is currently only for discussion purposes.

**Comment by metakuni** [comment]
See also mention of ontology usage in the [2024H1 Applications Roadmap](https://docs.google.com/document/d/1vVarBijE2lVoZAwp_sGiERyW9vYMnaIR2vganmuNlpI/edit)

**Comment by metakuni** [comment]
Note: This epic's initial start/end dates are based on t-shirt estimates. The end date will be refined after the discovery work and the tech spec is completed.

**Comment by metakuni** [comment]
See also mention here:
* [tissue_mapper.py should be owned by Census and not data portal #841](https://github.com/chanzuckerberg/cellxgene-census/issues/841)

**Comment by Bento007** [comment]
> We should investigate integrating all required ontology processing into the ontology preparation step for the cellxgene-schema CLI to eliminate duplication of code and ensure that all features are based on the pinned versions of the ontologies.

This too opinionated on implementation. There are other way we can approach this to consider.
- keep in the cli
- stand up our own service
- create separate library.

**Comment by brianraymor** [comment]
@Bento007 - I completely agree with your "too opinionated". 

In addition, there is a stronger **signal** to expose external access to some features  to data consumers. There have been multiple requests on #cellxgene-census-users in CZI Science Community:

* Tissue Mapping
* Cell Type Mapping
* [Descendants of Cell Type](https://cziscience.slack.com/archives/C04LMG88VKJ/p1701194355216319?thread_ts=1701132526.122309&cid=C04LMG88VKJ)

There's also strong interest in reusing our cell type and tissue mappings based on recent conversations with a **private partner** as reported by @ambrosejcarr. 

---

**Comment by Bento007** [comment]
Discovery work is complete
