### ISSUE TITLE
Add tissue_type

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#459]
**Note**: This is a placeholder epic for Dev to add child issues following an assessment of required changes. 

The changes to the cellxgene-schema CLI are tracked separately in [cellxgene-schema must validate tissue_type](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/514)

# Design

This also changes the validation and label application for `tissue_ontology_term_id` and `tissue`.

See [tissue_type](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#tissue_type).

### tissue_type

<table><tbody>
    <tr>
      <th>Key</th>
      <td>tissue_type</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"tissue"</code>, <code>"organoid"</code>, or <code>"cell culture"</code>.
    </tr>
</tbody></table>
<br>

### tissue_ontology_term_id

<table><tbody>
    <tr>
      <th>Key</th>
      <td>tissue_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
   <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. If <code>tissue_type</code> is <code>"tissue"</code> or <code>"organoid"</code>, this MUST be the most accurate child of <a href="https://www.ebi.ac.uk/ols4/ontologies/uberon/classes?obo_id=UBERON%3A0001062"><code>UBERON:0001062</code></a> for <i>anatomical entity</i>.<br><br> If <code>tissue_type</code> is <code>"cell culture"</code> this MUST follow the requirements for <code>cell_type_ontology_term_id<code>.</td>
     </tr>
</tbody></table>
<br>

### tissue

<table><tbody>
    <tr>
      <th>Key</th>
      <td>tissue</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be the human-readable name assigned to the value of <code>tissue_ontology_term_id</code>.
        </td>
    </tr>
</tbody></table>

---

# Data Platform

**Note**: Still sketching out the potential changes

1. `tissue_type` must be stored in the database similar to other dataset metadata.
1. `tissue_type` must be returned in the Discover and Data Portal filter API(s).  **MUST be refined**.
1. `tissue_type` must be added as a new Collection and Dataset UX Filter. **MUST be refined**.

Also see the [conversation](https://czi-sci.slack.com/archives/C03PXFMM7ST/p1693339054543399?thread_ts=1693333761.816239&cid=C03PXFMM7ST) with @jahilton.

# Data Viz

1. `tissue_type` must be displayed in *Standard Categories* or dataset drawer in Single Cell Explorer. 
1. This impacts any [special processing or filtering](https://github.com/chanzuckerberg/single-cell-data-portal/blob/e20edec161fc78a8c7a37048031b25ed2a8f819f/backend/wmg/data/ontology_labels.py#L20) related to "organoids" or "cell culture" in `tissue_ontology_term_id` and `tissue`.
1. The WMG processing pipeline should be updated to exclude "non-tissue" tissues from the generated cubes.

# Census

1. This impacts any [special processing or filtering](https://github.com/search?q=repo%3Achanzuckerberg%2Fcellxgene-census%20%20organoid&type=code) related to "organoids" or "cell culture" in `tissue_ontology_term_id` and `tissue`.
2. `tissue_type` must be added to the Census schema.
3. `tissue_type` must be added to the Census builder.

**Comment by prathapsridharan** [comment]
@atarashansky @signechambers1 (cc: @dsadgat @joyceyan )

This is in regards to the `data-viz` part of the requirement in the description:

1. If `tissue_type` is to be added to `explorer`, should it show up under the [Standard Categories on the left side pane](https://cellxgene.cziscience.com/e/9c63201d-bfd9-41a8-bbbc-18d947556f3d.cxg/)? Currently the list show is `[cell type, development stage, donor id, sex, tissue]` - _Should `tissue_type` be an addition to this list in explorer?_
2. If so, we would need to make changes the to the filtering logic too. I think that might be a fair bit of work if you we consider the timeline for schema 4 (Nov 4) and also having to test this. _Could this particular change to explorer be done after schema 4 migration?_ The reason being that since it is a brand new field, this particular change to the data schema is backward compatible with the reader of the data (explorer)

**Comment by signechambers1** [comment]
@prathapsridharan in response to your questions:
1. Yes, if tissue_type has multiple values it should show up under Standard Categories. If it is a singleton value across the entire dataset I would expect it to show up in the dataset drawer.
2. What filtering logic are you speaking of? Surfacing the value can happen after the schema 4 migration.
