### ISSUE TITLE
Design UI for resumable downloads

### ISSUE THREAD

**Issue by pdugan20** [chanzuckerberg/single-cell#46]
The data portal interface should support a user being able to pause and restart the download of a larger dataset. The UI should make considerations re: reusable designs and components to in the future support resumable uploads

**Comment by pdugan20** [comment]
Work in progress designs will live here: https://www.figma.com/file/hy3wOqrKbunH1C3lA7CuP6/download-dataset?node-id=0%3A1. We'll use the existing download dataset modal as a jumping off point as we move these designs along.

**Comment by brianraymor** [comment]
Per discussion with @tihuan and @mckinsel - _resumable_ downloads are paused until we have more signal from users.
