### ISSUE TITLE
Update self_reported_ethnicity

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#460]
Note: This is a placeholder epic for Dev to add child issues following an assessment of required changes. 

See [**#single-cell-data-wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1690504193543139?thread_ts=1686097986.283929&cid=C024HCSH9PT) for discussion with @norbid about his preferences for how multiple self reported ethnicity values may be surfaced in the CELLxGENE Discover UX. 

The changes to the cellxgene-schema CLI are tracked separately in [cellxgene-schema must validate self_reported_ethnicity](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/515)

# Design

See [schema 4](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#self_reported_ethnicity_ontology_term_id)

### self_reported_ethnicity_ontology_term_id

<table>
  <tbody>
    <tr>
      <th>Key</th>
      <td>self_reported_ethnicity_ontology_term_id</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>Curator</td>
    </tr>
    <tr>
      <th>Value</th>
      <td>
        categorical with <code>str</code> categories. If
        <code>organism_ontolology_term_id</code> is
        <code>"NCBITaxon:9606"</code> for <i>Homo sapiens</i>,
        the value MUST be formatted as one or more comma-separated (with no leading or trailing spaces) HANCESTRO
        terms in ascending lexical order or <code>"unknown"</code> if unavailable.<br><br>For example, if the terms are <code>"HANCESTRO:0014</code> and <code>HANCESTRO:0005"</code> then the value of <code>self_reported_ethnicity_ontology_term_id</code> MUST be <code>"HANCESTRO:0005,HANCESTRO:0014"</code>.<br><br>The following terms MUST NOT be used:<br /><br />
        <ul>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0002?lang=en"
              ><code>"HANCESTRO:0002"</code></a
            >
            for <i>regions</i> and its children
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0003?lang=en"
              ><code>"HANCESTRO:0003"</code></a
            >
            for <i>country</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0004?lang=en"
              ><code>"HANCESTRO:0004"</code></a
            >
            for <i>ancestry category</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0018?lang=en"
              ><code>"HANCESTRO:0018"</code></a
            >
            for <i>uncategorised population</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0290?lang=en"
              ><code>"HANCESTRO:0290"</code></a
            >
            for <i>genetically isolated population</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0304?lang=en"
              ><code>"HANCESTRO:0304"</code></a
            >
            for <i>ancestry status</i> and its children
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0323?lang=en"
              ><code>"HANCESTRO:0323"</code></a
            >
            for <i>Finnish founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0324?lang=en"
              ><code>"HANCESTRO:0324"</code></a
            >
            for <i>Dutch founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0551?lang=en"
              ><code>"HANCESTRO:0551"</code></a
            >
            for <i>genetically homogenous Irish</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0554?lang=en"
              ><code>"HANCESTRO:0554"</code></a
            >
            for <i>Silk Road founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0555?lang=en"
              ><code>"HANCESTRO:0555"</code></a
            >
            for <i>Arab Israeli founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0557?lang=en"
              ><code>"HANCESTRO:0557"</code></a
            >
            for <i>Costa Rican founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0558?lang=en"
              ><code>"HANCESTRO:0558"</code></a
            >
            for <i>French Canadian founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0559?lang=en"
              ><code>"HANCESTRO:0559"</code></a
            >
            for <i>Italian founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0560?lang=en"
              ><code>"HANCESTRO:0560"</code></a
            >
            for <i>Northern Finnish founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0561?lang=en"
              ><code>"HANCESTRO:0561"</code></a
            >
            for <i>Romanian founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0564?lang=en"
              ><code>"HANCESTRO:0564"</code></a
            >
            for <i>Vis founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0565?lang=en"
              ><code>"HANCESTRO:0565"</code></a
            >
            for <i>Split founder</i>
          </li>
          <li>
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0566?lang=en"
              ><code>"HANCESTRO:0566"</code></a
            >
            for <i>undefined ancestry population</i>
          </li>
          <li>
            The imported GEO term
            <a
              href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGEO_000000374?lang=en"
              ><code>"GEO:000000374"</code></a
            >
            for <i>continent</i> and its children:
            <ul>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0029?lang=en"
                  ><code>"HANCESTRO:0029"</code></a
                >
                for <i>Africa</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0030?lang=en"
                  ><code>"HANCESTRO:0030"</code></a
                >
                for <i>Asia</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0031?lang=en"
                  ><code>"HANCESTRO:0031"</code></a
                >
                for <i>Europe</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0032?lang=en"
                  ><code>"HANCESTRO:0032"</code></a
                >
                for <i>Oceania</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0033?lang=en"
                  ><code>"HANCESTRO:0033"</code></a
                >
                for <i>Latin America and the Caribbean</i>
              </li>
              <li>
                <a
                  href="https://www.ebi.ac.uk/ols4/ontologies/hancestro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0034?lang=en"
                  ><code>"HANCESTRO:0034"</code></a
                >
                for <i>Northern America</i>
              </li>
            </ul>
          </li>
        </ul>
        <br />Otherwise, for all other organisms the
        <code>str</code> value MUST be <code>"na"</code>.
      </td>
    </tr>
  </tbody>
</table>
<br />

---

### self_reported_ethnicity

<table><tbody>
    <tr>
      <th>Key</th>
      <td>self_reported_ethnicity</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td>categorical with <code>str</code> categories. This MUST be <code>"na"</code> or <code>"unknown"</code> if set in <code>self_reported_ethnicity_ontology_term_id</code>; otherwise, this MUST be one or more comma-separated (with no leading or trailing spaces) human-readable names for the terms in <code>self_reported_ethnicity_ontology_term_id</code> in the same order.<br><br> For example, if the value of <code>self_reported_ethnicity_ontology_term_id</code> is <code>"HANCESTRO:0005,HANCESTRO:0014"</code> then the value of <code>self_reported_ethnicity</code> is <code>"European,Hispanic or Latin American"</code>.
        </td>
    </tr>
</tbody></table>
<br>

# Samples

## Sample normalized terms

```
adata.obs['self_reported_ethnicity_term_id'][0] = “HANCESTRO:0008”
adata.obs['self_reported_ethnicity_term_id'][1] = “HANCESTRO:0008,HANCESTRO:0320,HANCESTRO:0405”
adata.obs['self_reported_ethnicity_term_id'][2] = “HANCESTRO:0405”
adata.obs['self_reported_ethnicity_term_id'][3] = “HANCESTRO:0005”
adata.obs['self_reported_ethnicity_term_id'][4] = “HANCESTRO:0008”
adata.obs['self_reported_ethnicity_term_id'][5] = “HANCESTRO:0320”
adata.obs['self_reported_ethnicity_term_id'][6] = “HANCESTRO:0008,HANCESTRO:0320,HANCESTRO:0405”
adata.obs['self_reported_ethnicity_term_id'][7] = “unknown”

```

## Sample labels for terms

```
adata.obs['self_reported_ethnicity'][0] = “Asian”
adata.obs['self_reported_ethnicity'][1] = “Asian,Dutch,Cuban”
adata.obs['self_reported_ethnicity'][2] = “Cuban”
adata.obs['self_reported_ethnicity'][3] = “European”
adata.obs['self_reported_ethnicity'][4] = “Asian”
adata.obs['self_reported_ethnicity'][5] = “Dutch”
adata.obs['self_reported_ethnicity'][6] = “Asian,Dutch,Cuban”
adata.obs['self_reported_ethnicity][7] = “unknown”

```

# Data Platform

## Data Portal API changes

There should be no required changes to the current implementation. Based on the dataset samples above, the response value for `self_reported_ethnicity` would be:

```
'self_reported_ethnicity': [{'label': 'Asian',
                               'ontology_term_id': 'HANCESTRO:0008'},
                              {'label': 'Asian,Dutch,Cuban',
                               'ontology_term_id': 'HANCESTRO:0008,HANCESTRO:0320,HANCESTRO:0405'},
                              {'label': 'Cuban',
                               'ontology_term_id': 'HANCESTRO:0320'},
                              {'label': 'Dutch',
                               'ontology_term_id': 'HANCESTRO:0405'},
                              {'label': 'European',
                               'ontology_term_id': 'HANCESTRO:0005'},
                              {'label': 'unknown',
                               'ontology_term_id': 'unknown'}]
```

## Discover API changes

There should be no required changes to the current implementation. Based on the dataset samples above, the response value for `self_reported_ethnicity` would be:

```
'self_reported_ethnicity': [{'label': 'Asian',
                               'ontology_term_id': 'HANCESTRO:0008'},
                              {'label': 'Asian,Dutch,Cuban',
                               'ontology_term_id': 'HANCESTRO:0008,HANCESTRO:0320,HANCESTRO:0405'},
                              {'label': 'Cuban',
                               'ontology_term_id': 'HANCESTRO:0320'},
                              {'label': 'Dutch',
                               'ontology_term_id': 'HANCESTRO:0405'},
                              {'label': 'European',
                               'ontology_term_id': 'HANCESTRO:0005'},
                              {'label': 'unknown',
                               'ontology_term_id': 'unknown'}]
```

## Discover UX filter changes

Refined into [Self-Reported Ethnicity filter in Collections and Datasets must be updated](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5875)

# Data Viz

1. [This function](https://github.com/chanzuckerberg/single-cell-data-portal/blob/13eede80b816391ade541ef8828e572704e1d214/backend/wmg/data/ontology_labels.py#L23) in the WMG processing pipeline must be updated to appropriately handle ethnicity term strings with comma-separated values.
2. WMG frontend filter should be updated to exclude multiethnic terms, same with the compare feature.

# Census

1. Depending on the final modeling of the new values, it may require Census schema changes and Census Builder changes. May introduce a breaking change in the data (i.e. previous external pipelines using the Census can break)

**Comment by prathapsridharan** [comment]
@brianraymor (cc: @atarashansky @dsadgat @joyceyan)  - Will the schema CLI fail validation if it encounters values like the following. The list below is not exhaustive but giving examples of stuff that doesn't make sense:

1. `unknown,HANCESTRO:0008`
2. `HANCESTRO:0008,unknown,HANCESTRO:0320`
3. `unknown,na`

I ask because it affects implementation in gene expression application
