### ISSUE TITLE
Add citation

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#462]
**Note**: This is a placeholder epic for Dev to add child issues following an assessment of required changes. 

# Design

See [citation](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#citation). 

When a dataset is uploaded, CELLxGENE Discover MUST automatically add the `citation` key and set its value.

### citation

<table><tbody>
    <tr>
      <th>Key</th>
      <td>citation</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>. Its format MUST use the following template:
          <br><br>
          <table>
          <thead>
          <tr>
          <th>Citation Element</th>
          <th>Value</th>
          </tr>
          </thead>
          <tbody>
            <tr>
              <td><i><code>"Publication: "</code></i></td>
              <td>Publication DOI url for the collection<br><br> This element MUST only be present if a<br> Publication DOI is defined for the collection;<br> otherwise, it MUST NOT be present.</td>
            </tr>
            <tr>
              <td><i><code>"Dataset Version: "</code></i></td>
              <td>Permanent url to this version of the dataset</td>
            </tr>
              <td><i><code>" curated and distributed by<br> CZ CELLxGENE Discover in Collection: "</code> </i></td>
              <td>Permanent url to the collection</td>
            </tr>
          </tbody></table>
          A citation for a H5AD dataset with a Publication DOI:<br><br>"<code><b>Publication:</b> https://doi.org/10.1126/science.abl4896 <b>Dataset Version:</b> https://datasets.cellxgene.cziscience.com/dbd8b789-3efa-4a63-9243-90cff64f2045.h5ad <b>curated and distributed by CZ CELLxGENE Discover in Collection:</b> https://cellxgene.cziscience.com/collections/e5f58829-1a66-40b5-a624-9046778e74f5"</code><br><br>
          A citation for a RDS dataset without a Publication DOI:<br><br><code>"<b>Dataset Version:</b> https://datasets.cellxgene.cziscience.com/08ea16dc-3f4e-4c84-8692-74d70be22d12.rds <b>curated and distributed by CZ CELLxGENE Discover in Collection:</b> https://cellxgene.cziscience.com/collections/10bf5c50-8d85-4c5f-94b4-22c1363d9f31"</code><br><br>
        </td>
    </tr>
</tbody></table>

---

# Data Platform
1. During upload processing for new or updated datasets, its citation must be added to the H5AD and RDS datasets.
1. For revisions that add or change the Publication DOI, the citations for all datasets in the collection must be updated.
1. `citation` must be stored in the database similar to other dataset metadata.
1. `citation` must be returned in the Discover API. **Needs specific endpoints and modeling**. 

**Note**:  For the revisions case, @nayib-jose-gloria proposed an alternative - update the embedded citation during a regular migration of the data corpus. 

## Out of Scope

There are no current plans to surface the citation in the Discover UX:

1. `citation` must be returned in the Data Portal API. **Needs specific endpoints and modeling**.  

# Data-Viz
1. `citation` _could_ be displayed in the dataset drawer in Single Cell Explorer with other `uns` data. Note: this requires no changes to support.

# Census

Census has been refined.

**Comment by joyceyan** [comment]
@signechambers1 Not sure if you've seen this ticket yet, but now that we'll have this data available in schema 4, we could potentially add this to Explorer based on this comment here in the ticket body:
> `citation` _could_ be displayed in the dataset drawer in Single Cell Explorer with other uns data. Note: this requires no changes to support.

I don't see a ticket within this epic to reflect this work. Do you think this is something we would want to do, or does the lack of ticket reflect that this isn't important (or is being tracked somewhere else?).
