### ISSUE TITLE
Implement commonly used algorithms to Census experimental API

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell#469]
[To be refined]

This epic will be used to capture all the work necessary to add implement commonly used algorithms. In H1, 2023 we introduced an out-of-core implementation of Scanpy's highly-variable genes.

This is the initial candidate list, for any given slice of the Census:

- Find marker genes.
- Out-of-core row-based (cells) average and variances.
- Differential gene expression.
- Scalable knn graph generation 
- Scalable MDE/UMAP.

## Anticipated resources

- 6 weeks engineering work
- 2 weeks PM work

**Comment by allisonbrownczi** [comment]
@pablo-gar I think you have the wrong person, unassigning myself

**Comment by pablo-gar** [comment]
completed for now H2
