### ISSUE TITLE
Add observation_joinid

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#471]
**Note**: This is a placeholder epic for Dev to add child issues following an assessment of required changes. 

The changes to the cellxgene-schema CLI are tracked separately in [cellxgene-schema must annotate observation_joinid](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-curation/523)

# Design

When a dataset is uploaded, CELLxGENE Discover MUST annotate a unique observation identifier for each cell. Curators MUST NOT annotate the following column.

### observation_joinid

<table><tbody>
    <tr>
      <th>Key</th>
      <td>observation_joinid</td>
    </tr>
    <tr>
      <th>Annotator</th>
      <td>CELLxGENE Discover</td>
    </tr>
    <tr>
      <th>Value</th>
        <td><code>str</code>
    </tr>
</tbody></table>
<br>

---

# Data Platform
1.  There's no rationale to include `observation_joinid` in Discover API responses. Beyond annotation during ingestion, no further work is required. 

# Census

1.  @brianraymor added census related issues from that repo
2.
3. 

# Data-Viz
1. This field MUST NOT be displayed in Explorer `Standard Categories`.

**Comment by brianraymor** [comment]
@pablo-gar - I added all the census `observation_joinid` issues that were open in cell census. Please review and update as needed.

**Comment by prathapsridharan** [comment]
@joyceyan @atarashansky @nayib-jose-gloria - For data-viz does that mean that the list `STANDARD_CATEGORY_NAMES` does not contain `observation_joinid` which it currently does not:

https://github.com/chanzuckerberg/single-cell-explorer/blob/64316e0566b1bda2224f4b29825ae2d4e4f03c30/client/src/common/types/entities.ts#L7

Does that mean there is nothing to do here for `Explorer`?

**Comment by nayib-jose-gloria** [comment]
I think you're right that there is no work required to stop it from appearing in Standard Categories. While not listed in the ticket, I actually think we also want to prevent this from appearing as an 'Author Category', which is I believe is currently determined as any obs field that is not in the Standard Category list. So you may need to introduce a denylist that includes observation_joinid and check it when determining Author Categories. But you should confirm with the product owner for Explorer

**Comment by prathapsridharan** [comment]
Thanks @nayib-jose-gloria. @signechambers1 - could you please confirm what @nayib-jose-gloria says above? I have created the following ticket in anticipation of a confirmation:

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/597

**Comment by brianraymor** [comment]
There may also be some confusion because the original census draft/prototype proposed a uint64 type which would have been filtered out by https://github.com/chanzuckerberg/single-cell-explorer/issues/644. The type had to be changed to a string due to R limitations. Also see [**single-cell-census**](https://czi-sci.slack.com/archives/C048BN7K6U8/p1690396401300579). 

This is not a useful field for Explorer.

**Comment by signechambers1** [comment]
@prathapsridharan confirmed, we do not want observation_joinid to be surfaced in Explorer in Author Categories (or Standard Categories). Thank you @nayib-jose-gloria!
