### ISSUE TITLE
Finalized manuscript draft

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell#476]
Target date: August 7

[Working Draft](https://docs.google.com/document/d/1RrnIbH0Mflm1_Qactm6bWxWvQnUd-Gc5u5V7P8dxNf8/edit)

**Comment by brianraymor** [comment]
@ainfeld - can this be closed?

**Comment by ainfeld** [comment]
@brianraymor let me confirm with Bailey since she was the owner of this. I just added the issues because she was having a problem accessing Zenhub. I should've noted the real owner of these. Apologies for the confusion.
