### ISSUE TITLE
Integrated object accessible for preprint release

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell#481]
**Data Stories:**

- At the time of preprint or manuscript publication, a reader MUST be able to find and access (or generate) data that approximately match the data that power Gene Expression, so that reviewers can evaluate our methods choices.
- Gene expression data that users find and access (or generate) through preprints or manuscripts MAY or MAY NOT change to reflect updated data, at our discretion.
- As a data visualization leader, I need to know how many users find and access (or generate) the above data so that I can make informed decisions about whether or not to invest additional effort in this feature in the future.

**Assertion:** In H2 2023, there will be two publishing points when data need to be updated: when the preprint is published, and when the manuscript is published.
**Assertion:** No biological findings derived from the Gene Expression interface will be published in the preprint or the manuscript, and therefore data do not need to be archived for future reproduction (there are currently no findings in the manuscript).

**Draft Docs Stories:**
- As a scientist, when I navigate from the preprint to the docs site, I need to be linked directly to the section that describes how to download the data so that I don't waste time scrolling, trying to find it.

Note: Depending on docs site characteristics, this may necessitate a new page for hosting data. 
* If linking to sections is possible, adding a section at the bottom of [this page](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_3__Gene%20Expression%20Data%20Processing) is preferred.
* If linking to sections is not possible, adding a new page is preferred. 

**Draft page language:**

*Gene Expression Source Data (Section Header)*

*Two versions of Gene Expression data can be downloaded. The full dataset, containing <eng describe + link>, and a condensed format designed for easier use <eng describe + link>.*

**Implementation Notes**

In order to satisfy the above, lets download CSVs of the data powering GE and provide a link to those in the docs site, with some additional verbiage on the docs site.

Notes: 
- Download links should be in docs site, docs link should be in pre-print - please attach link here. 
  - [bookmark](https://docs.google.com/document/d/1RrnIbH0Mflm1_Qactm6bWxWvQnUd-Gc5u5V7P8dxNf8/edit#bookmark=id.yan7lfbcysyf) to paragraph describing data in manuscript
- Verbiage on the site will be written and provided to Engineering to include in docs site by @ambrosejcarr .
- Ensure (should be automatic if in S3?) there is analytics surrounding clicking the download links.

Target date: August 4th delivery to Bailey

**Comment by ambrosejcarr** [comment]
@dsadgat please see updated epic for: 
- additional docs site related story about user linking + page suggestions
- draft language for docs site + request for eng help specifying the two objects
- link to manuscript draft where language will be mirrored + placeholder text matching the draft language added to this epic

**Comment by atolopko-czi** [comment]
@atarashansky Before closing out this issue, please add mention of the new bucket and data to the Tech Overview doc. Ty!
