### ISSUE TITLE
Validation of integration methodology

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell#483]

**Comment by maniarathi** [comment]
Hey @ainfeld -- I think this is a duplicate of #472 (https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/472). Is that correct or does this work refer to something else? Thanks!

**Comment by ainfeld** [comment]
@maniarathi that might be, I would check with Bailey

**Comment by pancakesforlife** [comment]
Yes this was made before anyone was assigned to this project. Will (attempt to) close!
