### ISSUE TITLE
Investigate + Resolve Upload SFN Job Timeouts in Migration Runs

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell#517]
About 10-15 DownloadValidate / Seurat Conversion Timeouts occurred during dev Schema Migration run. Consider increasing the timeout for these jobs to match CXG conversion, what automated retry options exist and would be sufficient, or if its best resolved by provisioning greater resources.

[Example](https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/v2/executions/details/arn:aws:states:us-west-2:699936264352:execution:dp-dev-devstack-sfn:48b2dd01-187b-4959-87c7-39f5ec610c37):

**Comment by Bento007** [comment]
There is already a retry strategy implemented and should retry up to 3 times.
