### ISSUE TITLE
feat(schema4): remove redundant code for dealing with root CL terms

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell#527]
NOTE: This should also be completed after the schema 4 migration is completed.

**Comment by nayib-jose-gloria** [comment]
Should be done AFTER schema 4.0.0 migration is complete, though as far as I understand it is not urgent because it will be a no-op even if it stays. Schema 4.0.0 will no longer allow the IDs we're filtering out here anyway, so this is good clean-up to track.

@atarashansky / @dsadgat

**Comment by joyceyan** [comment]
@nayib-jose-gloria @atarashansky Do you know where in the codebase this would be, just so we have a sense of a time estimate for this ticket? I'm marking it as a P2 since it seems we can do this after the schema 4 migration and even then is non-urgent.

**Comment by atarashansky** [comment]
Frontend: https://github.com/chanzuckerberg/single-cell-data-portal/blob/dd9c0a22f210601bce0074111f6cceee489a1d96/frontend/src/common/queries/wheresMyGene.ts#L516

Backend: https://github.com/chanzuckerberg/single-cell-data-portal/blob/dd9c0a22f210601bce0074111f6cceee489a1d96/backend/wmg/pipeline/cell_type_ordering.py#L127

**Comment by joyceyan** [comment]
Thanks! Should be pretty easy then :)
