### ISSUE TITLE
In prep for a schema migration, only bump schema version in cellxgene-schema CLI as part of an automated PR

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell#545]
The initial implementation for schema migration automation after a reference file [bump](https://github.com/chanzuckerberg/single-cell-curation/blob/main/.github/workflows/schema-version-bump.yml) includes steps for bumping the schema version + creating new release tags and pushing these changes directly to main as part of the workflow. This required loosening the branch protections on this repo, and Central Infra requested that we do not do so. Further, we open a PR as an output of this workflow anyway so it seems reasonable to just capture all schema bumps as part of the PR. For minor schema updates, the bump should be to the minor part of the semver, and for major schema updates to the major part. 

This also means getting rid of [this](https://github.com/chanzuckerberg/single-cell-curation/blob/main/.github/workflows/schema-version-bump.yml#L106) intermediate PyPI publish step in the workflow, which was initially included to start gating dataset uploads in the data portal to new schema validation rules even before migration occurs. But, in practice, we've realized this step is unnecessary and not particularly more useful than just publishing 1 PyPI package with the migration script + new validation rules at the same time.

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria could I get a couple sentences' description here from you just to flesh out the precise issue

**Comment by nayib-jose-gloria** [comment]
@danieljhegeman updated, thanks for the reminder
