### ISSUE TITLE
Productionalize Frontend Filter Compute Scripts

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell#555]
In [single-cell-curation](https://github.com/chanzuckerberg/single-cell-curation/tree/main/scripts/compute_mappings)

Add Unit Tests
Refactor python scripts 
Deprecate python notebook version (or, at minimum, decouple from the python scripts and don't require generating changes from one to the other)

**Comment by danieljhegeman** [comment]
Initial discussion with @nayib-jose-gloria suggests these scripts, while perhaps not organized a super pretty fashion at the moment, are 1) not something that need to be updated (on a regular basis), and 2) function just fine as they are now. I propose that we decrease priority to p2 or even p3.

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria can we confirm that this ticket was meant to apply **only** to the FE Filter Compute notebooks, and not also to the Curation API notebooks? cc @metakuni

**Comment by nayib-jose-gloria** [comment]
@danieljhegeman correct

**Comment by danieljhegeman** [comment]
>(or, at minimum, decouple from the python scripts and don't require generating changes from one to the other)

It is not clear to me what this is meant to entail. Neither of the two compute notebooks imports code from _any_ python scripts (the only imports are packages).

EDIT: the scripts appear to just be copied from the notebooks

**Comment by danieljhegeman** [comment]
module is missing `graphviz` as a required program ahead of `pip`-installing python packges

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria the `../utils/ontology_mappings/constants.py` file referenced [here](https://github.com/chanzuckerberg/single-cell-curation/blob/aff77830f3da84c927f0bb8905493970ad3840bb/scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py#L14) doesn't exist. And it isn't clear from searching git log data where it might've moved to.

**Comment by nayib-jose-gloria** [comment]
> @nayib-jose-gloria the `../utils/ontology_mappings/constants.py` file referenced [here](https://github.com/chanzuckerberg/single-cell-curation/blob/aff77830f3da84c927f0bb8905493970ad3840bb/scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py#L14) doesn't exist. And it isn't clear from searching git log data where it might've moved to.

https://github.com/chanzuckerberg/single-cell-data-portal/tree/main/backend/common/utils/ontology_mappings/fixtures

they've been split across these fixtures

**Comment by danieljhegeman** [comment]
@pablo-gar just want to surface one little thing:

There are [two functions](https://github.com/chanzuckerberg/single-cell-curation/blob/aff77830f3da84c927f0bb8905493970ad3840bb/scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py#L506-L559) which find the set of ancestors for a given node, and the set of descendants for a given node, respectively. The ancestor function is **including** the node itself, and the descendant function is **excluding** the node. Can you confirm this asymmetric behavior is intended?

**Comment by danieljhegeman** [comment]
Need to confirm whether checking is_organoid strictly for `"(organoid)"` while key_organoids_by_ontology_term does a `.replace(" (organoid)", "")` is intended. Note leading space in the latter. Could cause organoids formatted as `<ontology_term_id>(organoid)` to not be included in tissue descendants writeout.

EDIT Answered: validation ensures that format will be `" (organoid)"`.

**Comment by MillenniumFalconMechanic** [comment]
Hey @danieljhegeman, `tissue_ancestors` should include the tissue itself. Multi-panel filters (tissue and cell type) execute an "includes" on their respective `${filterName}_ancestors` field to determine if a dataset (or collection) is to be included in the result set. For example, for a tissue of a given dataset, you want that dataset included in the result set if the tissue (or any of the tissue's ancestors) is selected in the filter.

_Descendants_ back cross-panel filtering within a multi-panel filter and do not need to include the tissue itself. That is, for a selected tissue in a multi-panel filter, you only want to include descendants of the selected tissue in "child panels" of the filter.

**Comment by danieljhegeman** [comment]
@MillenniumFalconMechanic sounds good, thanks for confirming!

**Comment by danieljhegeman** [comment]
Moving back to Disorder until I can come back to reconcile the added unit tests with the changes introduced by CC/Mim.
