### ISSUE TITLE
Only Report Prod Schema Migrations in Curator-Reports Slack Channel

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell#558]
Create separate channel for rdev/dev/staging test runs, or find another way of delivering the report without creating noise for curators.

**Comment by danieljhegeman** [comment]
> Create separate channel for rdev/dev/staging test runs

I think this is actually a good idea, because it would give us the ability to test Slack error messages in development environments, something we don't currently have, and which I would've liked for a recent ticket that I completed.

**Comment by danieljhegeman** [comment]
Changed the slack_reporter_channel secret to point to new channel for dev and staging. Channels will start receiving migration reports after next deploy / service restart. Will also add deployment stage note in the report header so that dev and staging can be distinguished.
