### ISSUE TITLE
Fix JSON Serialization Error in publish_and_cleanup when reporting DatasetUploadStatus

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell#559]
See real migration run example: 
```
{
    "errors": [
        {
            "args": [],
            "error": "Object of type DatasetUploadStatus is not JSON serializable",
            "kwargs": {
                "can_publish": true,
                "collection_version_id": "<REDACTED>"
            },
            "step": "publish_and_cleanup"
        }
    ]
}
```

This occurs when reporting an error in a dataset's status during the publish and cleanup step (used to report that a publish was not done because of a dataset error)

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria is there any more context to give about when this is occurring? Perhaps a cloudwatch log trace?

**Comment by danieljhegeman** [comment]
Preliminary assumption is that [this](https://github.com/chanzuckerberg/single-cell-data-portal/blob/b7303ac5420933848e810f679ab19d02cd938c65/backend/layers/processing/schema_migration.py#L251) is where the error is coming from. A `DatasetUploadStatus` (along with other sub-categories of Dataset status) would be getting included in the `DatasetStatus` [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/b7303ac5420933848e810f679ab19d02cd938c65/backend/layers/processing/schema_migration.py#L219).

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria Pretty sure I have a fix for this at the level of preventing JSON serialization errors, which is just to have the `DatasetStatusGeneric` inherit from `str` in its definition... but at a service/logical level, it seems to me like this error should have been occurring for every single Dataset, every time. Any Dataset with a non-null...
- `DatasetUploadStatus`
- `DatasetValidationStatus`
- `DatasetConversionStatus`
- `DatasetProcessingStatus`
would, from my reading, produce this error...

**EDIT**: I retract the above assertion about expecting this error every time

**Comment by nayib-jose-gloria** [comment]
@danieljhegeman its possible we only try to log/json serialize on failures so we didn't notice this bug in other theoretical scenarios. Not sure though, something to look into

**Comment by Bento007** [comment]
are we using this encoder https://github.com/chanzuckerberg/single-cell-data-portal/blob/2d7bc6bb7e5fa303d1c72b308c2542a1a1ac2070/backend/common/utils/json.py#L16

**Comment by danieljhegeman** [comment]
> its possible we only try to log/json serialize on failures 

@nayib-jose-gloria  This is correct. But previously we were patching our way out of having to deal with it in the unit tests, so I added a side effect to the patch that tests JSON serializability.

**Comment by danieljhegeman** [comment]
@Bento007 added that to the json calls `cls=`
