### ISSUE TITLE
Create manual, isolated 'bulk publish' AWS job to publish all active revisions

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell#571]
Model after schema migration publish step (perhaps can re-use small or large portions?)

**Comment by Bento007** [comment]
Does this also mean remove the existing publish step at the end of migration?

**Comment by nayib-jose-gloria** [comment]
> Does this also mean remove the existing publish step at the end of migration?

I don't think so, we still want auto-publish for minor schema updates. I don't think its worth breaking that into two separate step functions if we don't have to, but lmk if you disagree

**Comment by Bento007** [comment]
Since this is supposed to be initiated via AWS, is there any kind of error reporting that needs to be propagated out to curators?

**Comment by nayib-jose-gloria** [comment]
> Since this is supposed to be initiated via AWS, is there any kind of error reporting that needs to be propagated out to curators?

the plan is that this would only ever be initiated by engineers during major schema updates (with curator approval), so error reporting should be geared towards things useful for engineers to debug
