### ISSUE TITLE
Convert Minor Schema Update GHA workflows to be manually dispatched

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell#573]
1) https://github.com/chanzuckerberg/single-cell-curation/blob/main/.github/workflows/minor-schema-version-bump.yml
2) https://github.com/chanzuckerberg/single-cell-curation/blob/main/.github/workflows/trigger-schema-migration.yml

Update both these workflows to be [manually dispatched](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) via the Github UI, as major schema updates may also include changes to the files in the provided trigger paths and should have manual dispatches by engineers upon request from Lattice/Product.

**Comment by danieljhegeman** [comment]
@nayib-jose-gloria I'm a bit confused: title specifies `Minor` but the description specifies `major`

edit: ok the first one is minor updates, and the second one is major version updates. 

and with 
>as major schema updates may also

the emphasis is on _may also_ i.e. similar to minor version bump
