### ISSUE TITLE
Use published DOI rather than preprint where exists

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell#575]
**The automated portion of this work is now captured/tracked [here](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6313)**
**The work attached to this ticket addresses the real-time check for published DOIs when a preprint DOI is submitted as part of Collection creation or Collection metadata update**

[Update the DOI in the A single-cell transcriptional roadmap of the mouse and human lymph node lymphatic vasculature collection](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-curation/106) is an example of an updated DOI that was discovered during prototyping. If an existing preprint  DOI is queried again AND it has been published since the previous query, then Crossref returns the published DOI in:

```
if is_preprint:
    try:
        published_doi = message['relation']['is-preprint-of']
       # the new DOI to query for ...
        if published_doi[0]['id-type'] == 'doi' :
            display(published_doi[0]['id'])
    except KeyError:
        pass
```

This would allow the portal to refresh preprint DOI(s) with their published DOI(s) on a regular cadence. 

Lattice discovered a case in the past where the publishers failed to update the relationship between a [preprint DOI](https://api.crossref.org/works/10.1101/2020.04.03.024075) and its [publication DOI](https://api.crossref.org/works/10.1038/s41586-020-2797-4). 

---

**Nayib's Note**: Implementation Idea to add a check for ‘is-preprint-of’ on every preprint DOI fetch and fetch that instead if a published DOI is found. Check if feasible or how often we do DOI fetches

**Comment by danieljhegeman** [comment]
> Nayib's Note: Implementation Idea to add a check for ‘is-preprint-of’ on every preprint DOI fetch and fetch that instead if a published DOI is found. Check if feasible or how often we do DOI fetches

This could be a viable strategy. Though, ideally we would push the check out as far as possible (without having a chron job that is constantly checking these values), and would therefore want to perform the check immediately before publish. This is more reason to move to an async publish strategy, as I previously hinted at as a solution for dealing with race conditions in dataset reprocessing as a result of [doi updates](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/5880).

This would obviously require some extensive discussion with Product.

**Comment by danieljhegeman** [comment]
At the same time, I am skeptical of this being an urgent issue. Do we have evidence that this has happened more than once? More than twice?

**Comment by nayib-jose-gloria** [comment]
@danieljhegeman its not urgent (its a p1) but it was a product request that has been on the board for a while and was pulled into this epic. I think we can recommend against implementing now or suggest a lighter scale implementation if we scope it out and think the work outweighs the reward. But we should provide our scoped out solution and reasoning to discuss with Brian.

**Comment by nayib-jose-gloria** [comment]
@danieljhegeman I think the preprint not being updated on-time is uncommon, but that's because Lattice is tasked with updating it manually when a published DOI is available. So this would, at minimum, automate a manual step from their process. Granted, I'm not sure how much time they actually spend on this, so we should still ask how big of a burden this is relative to the work required to automate

**Comment by danieljhegeman** [comment]
@brianraymor just want to get your approval on one aspect of the intended implementation behavior: In all cases, when a doi is fetched from CrossRef, if the doi is determined to be a preprint, we will check for the published doi. If the Crossref pull for the latter, published doi produces an error, we will default to using the preprint doi rather than erroring out. We will not have a mechanism to report in real-time to the user that the published doi fetch failed, though we will log it in the service logs. No particular reason to believe this will be a regular / real occurrence, but that's the planned edge case behavior.

**Comment by brianraymor** [comment]
Sounds like a reasonable fallback for an **edge case**. It would be helpful to surface to me in some manner so I could open a crossref support request to ensure that it is addressed.

**Comment by brianraymor** [comment]
And per @nayib-jose-gloria 's comments, this is a _nice-to-have_ for 2023. It could be addressed in 2024 with other crossref issues that are pending:

[Crossref must be queried for updates and corrections to author metadata](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6085)
[Cleanup crossref code](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/6166)

**Comment by danieljhegeman** [comment]
@brianraymor sounds good.

Also noting here that we will have to take care of the preprint logic at the `collection_migrate` step, not at the `dataset_migrate` step. See [explanation](https://czi-sci.slack.com/archives/C03PXFMM7ST/p1701390462792149).
