### ISSUE TITLE
Load dataset into memory during validation when adding labels.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell#581]
The cellxgene schema cli validation is optimized to run on machines with limit memory. This comes at the expense of more processing time. When ingesting a dataset into the data portal validation is run on the datasets using the limit memory approach. We can speed up the validation process by removing this constrain when running validation as part of the ingestion pipeline. 

Adding labels is generally only run when ingesting a datasets into the data portal and it also requires reading the datasets into memory. Given this, the datasets should be read into memory during validation if labels will be writen.

# Definition of Done
- Read dataset into memory if [add_labels_file](https://github.com/chanzuckerberg/single-cell-curation/blob/1f482ae1476498c6661024afc014930649fe2441/cellxgene_schema_cli/cellxgene_schema/validate.py#L1203) is not `None`

**Comment by nayib-jose-gloria** [comment]
completed in https://github.com/chanzuckerberg/single-cell-curation/pull/636
