### ISSUE TITLE
 Per-tier detailed information about the tier and the associated projects.

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell#589]
**Story**: I am a computational biologist who wants to get Census integrated embeddings and their models to perform downstream analysis in my platform and toolkit of choice, for example scanpy in Python.

**Substory**: I would like to read and follow some executable examples to learn how to access the assets that CELLxGENE hosts

**Product requirement**: Per-tier sites providing detailed information about the tier and the associated projects. 

- All tiers should provide a description of the tier.
- Tiers 2 and Tier 1 should provide links (for ease of viewing) to our own site with an embedded notebooks: tier-wide notebooks and project-specific notebooks.
- All tiers should provide per-project information and metadata:
   - Tier 3 per project info:
      - Title
      - Description
      - Submitter
      - Submitter affiliation
      - DOI [optional]
      - Model link [optional]
      - Embeddings link [optional]
      - Any other free-form links.
   - Tier 2 per project (embedding) info:
      - Title
      - Description
      - ID for loading
      - Submitter
      - Submitter affiliation
      - DOI [optional]
      - Model link [optional]
      - Notebooks links [optional]
      - Census LTS release associated with the contribution (specified as a Census LTS tag)
      - Experiment name (e.g., "homo_sapiens")
      - Measurement name (e.g., "RNA")
      - Contribution type:  the type of the data.  Currently must be "obs embedding".  Future extensions may include "gene embedding", etc.
   - Tier 1 per project info:
      - Title
      - Description
      - ID for loading 
      - Model parameters and embedding details – this information will be long format 2-3 paragraphs
      - Notebooks links [optional]

**Comment by dsadgat** [comment]
@pablo-gar can you make sure this is up to date?
