### ISSUE TITLE
Project-specific notebooks for CZI Hosted Projects (formerly Tier 2) and CZI Maintained Projects (formerly Tier 1) are embedded in the site 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell#591]
**Story**: I am a computational biologist who wants to get Census integrated embeddings and their models to perform downstream analysis in my platform and toolkit of choice, for example scanpy in Python

**Substory**: I know different integration approaches have different properties, and I would like to gain a high-level understanding of the analytical potential that each different integration has. I can follow analytical examples to ground my understanding. For example:

- For any given data, can I predict cell types or diseases? Or any other states?
- Can I map my own data to the embedding space? 
- Do the embeddings encode any biological and/or technical variance?
- Can I do in silico experimentation with the models to find candidate genes to go from one state into another?
- Can I perform differential gene expression?
- Can I visualize cells in a 2D integrated scatter plot?
- Can I perform graph-based analysis on the embedding space to learn new biology? 
- Can the embeddings map cells from different organisms?
- Etc  

**Product requirement**: Project-specific notebooks for CZI Hosted Projects (formerly Tier 2) and CZI Maintained Projects (formerly Tier 1) are embedding in the site 

**High-priority demonstations**

1. Visualizing a subset of cells in a 2D scatter map
2. Analysis on the neighbors graph for interesting findings.
3. Projecting any cells (census and non-census) into the embedding space.
4. Inference workflow with the actual model (not the embeddings):
   5. e.g. Cell type
   6. e.g. in-silico experimentation

**Comment by atarashansky** [comment]
Some notes for me

Model candidates:
Tier 2: Jure's model, scGPT, Tim NMF factors
Tier 1: SCVI, GeneFormer

GeneFormer + SCVI are the only ones with embeddings available atm.
Data will need to be subsetted in the tutorial notebooks.

 - notebooks with embeddings visualized
 - Graph-based analysis on embeddings - leiden clustering, trajectory analysis
 - Projecting new data onto embeddings (zero-shot models only)
 - Inference workflows (predictive annotation)
   - Vanilla cell type prediction
   - Gene perturbation

Prioritize Tier 1, then move on to Tier 2.

**Comment by dsadgat** [comment]
@atarashansky could you create tickets here please? Ty!

**Comment by dsadgat** [comment]
@atarashansky could you please close the completed tickets? And perhaps close this epic (as its completed, correct?) TY!
