### ISSUE TITLE
Submission process for CZI Hosted Projects (formerly Tier 2) and Community Projects (formerly Tier 3)

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/single-cell#593]
**Story**: I am the a CELLxGENE  team member responsible for submitting contributor’s information to CZI Hosted Projects (formerly Tier 2) or Community Projects (formerly Tier 3), and would like to do a submission of a contributor

**Substory**: I a CELLxGENE  team member want to easily ingest Census embeddings to CZI Hosted Projects (formerly Tier 2) from a contributor

**Product requirement**: A submission ingestion system. See current [proposal](https://docs.google.com/document/u/0/d/1B-r9N7puGVtEc0tEE3Xfmfbh1h8kk-WNStNK5b9M-MA/edit)

- It should be capable to ingest and host embeddings along metadata
- Ingested data must be able to connect to FE to showcase the information necessary.
- Policies and data requirements should exist.

**Substory**: I a CELLxGENE  team member want to update Community Projects (formerly Tier 3) information from a contributor’s info.

**Product requirement**: The website for Community Projects (formerly Tier 3) assets (as described in first user story) should be easily editable by PM

**Comment by dsadgat** [comment]
@seve could you create your FE ticket here pls! TY!
