### ISSUE TITLE
feat(schema4): WMG frontend should be updated to handle multiethnic terms

### ISSUE THREAD

**Issue by joyceyan** [chanzuckerberg/single-cell#596]
We should just exclude these from the frontend when a user selects an ethnicity or chooses to group by ethnicity.

**Comment by joyceyan** [comment]
@signechambers1 @atarashansky In the [parent epic for self_reported_ethnicity](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/460), it says "WMG frontend filter should be updated to exclude multiethnic terms, same with the compare feature". To clarify, does that mean we want to remove "admixed ancestry" from the filter dropdown?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTlwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--803425609ed2bb151a85a882dfcdf8172c5b72bf/image.png)

It's also not clear to me what the expected behavior should be for handling multiethnic terms on the frontend. I see two viable options:
- We could show all possible multiethnic permutations in the dropdown. Ex: "European, Hispanic or Latin American" and "European, African" would all show up as options in the dropdown
- After selecting an ethnicity from one of the existing options, we would want to show all cells that have that ethnicity in it. So, selecting "European" would give you cells that are labeled as: "European", "European, Hispanic or Latin American", and "European, African"

**Comment by atarashansky** [comment]
In schema 4, multi-ethnic terms will appear as comma-separated strings ("European, African"). We want to exclude these as options displayed to the user in the filter dropdown. Same with the compare feature.

> We could show all possible multiethnic permutations in the dropdown. Ex: "European, Hispanic or Latin American" and "European, African" would all show up as options in the dropdown

We should exclude these.

> After selecting an ethnicity from one of the existing options, we would want to show all cells that have that ethnicity in it. So, selecting "European" would give you cells that are labeled as: "European", "European, Hispanic or Latin American", and "European, African"

Not applicable as the multi-ethnic terms will be excluded

**Comment by atarashansky** [comment]
Basically, any option with a comma in it should be filtered out from the dropdown and hidden from the heatmap when comparing by ethnicity.

**Comment by joyceyan** [comment]
Gotcha - Just to be clear, we only want to exclude multi-ethnic terms if we are filtering on one or more ethnicities or grouping by ethnicity? Otherwise, we would want to continue including these cells?

**Comment by atarashansky** [comment]
Correct!

**Comment by prathapsridharan** [comment]
@atarashansky - Although this ticket is pertains to what is presented in the frontend, I think the filtering can be done on backend. That is when calling `/filters` just remove comma-delimited values from the `self_reported_ethnicity_terms` sent back to the frontend.

Similarly if the user picks `ethnicity` as the group-by dimension, we filter out the gene-expression and cell-counts dataframes which are grouped by `(tissue, cell, ethnicity)` when `compare-dim = ethnicity` [after this line](https://github.com/chanzuckerberg/single-cell-data-portal/blob/66dae73e893a8546d544c87ae98251c94b95a9f1/backend/wmg/api/v2.py#L88)

What do you think?

**Comment by signechambers1** [comment]
FYI: From Alec: "We decided to exclude multi-ethnic terms because the combinatorics would result in an unreasonable number of options for ethnicity. The multi-ethnic terms also aren't interpretable because some may identify as 80% one ethnicity and 20% the other, and vice-versa, and yet the two labels would be exactly the same."
