### ISSUE TITLE
Reset CXG datasets to be all at the same version

### ISSUE THREAD

**Issue by maniarathi** [chanzuckerberg/single-cell#60]
**Need**: The CXG format was developed pretty iteratively and the current datasets in cellxgene all conform to different versions of the CXG format. Some of the modifications to the CXG format over time were not recorded so even if two datasets show that they are on the same version of CXG, they actually might differ in structure. In the long run, this can cause data anomalies, incompatibilities, and will make migrations complicated in case we make changes to the CXG format in a way that is not backwards compatible.

In order to prevent these future issues, all existing datasets that are available to view via the Data Portal should be on the same version of CXG.

**Comment by brianraymor** [comment]
Per conversation with @maniarathi , this issue will be addressed when Pablo updates older datasets that use the original schema and reloads them into the portal (once revision is available). The CXG will be regenerated then. Closing.
