### ISSUE TITLE
[Discovery] Curators want collection revisions to be automated to increase their velocity

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#610]
# Context

@jychien wrote:

Here is my current process for a revision:
- download h5ad using Download UX
- read h5ad and make changes to something (something like cell type update or dataset title)
- drop portal specific columns
- save to h5ad
- upload the correct h5ad to the appropriate dataset_id

This process is relatively painless when it's a few dataset for the collection. But recently, I've had to do one with 20 datasets and another which had a 5-10Gb h5ad (which required me to have my EC2 running).

It would be great to somehow make this process semi-automated. Something like we do during [migration](https://github.com/chanzuckerberg/single-cell-curation/blob/317481092fca8532a6b825cfeb9c403ec9d7269d/cellxgene_schema_cli/cellxgene_schema/migrate.py#L50). It would be nice if something like this was in place independent of a full migration, especially if we want to be able to efficiently update cell types ontologies, where the revisions that need to be made are across multiple collections for multiple dataset.

**Comment by metakuni** [comment]
Needs engineering discovery

**Comment by Bento007** [comment]
This would require updating all of the downstream assets(CXG and seurat). An MVP could be to create an API endpoint to allow some datasets fields to be modified that are compatible with light reprocessing.

**Comment by danieljhegeman** [comment]
Just a thought: it seems like we'd want to avoid requiring the curators to upload the same `X` matrix more than once, under any circumstances. It would be nice to have a revision paradigm that accepted metadata submissions which we then attach to the original h5ad objects. It could also reduce the validation time (i.e. no need to validate the same `X` and `raw.X` twice). Something to consider. It might be over-engineering for the given situation... or it might not. Similar to _light metadata reprocessing_...

**Comment by nayib-jose-gloria** [comment]
Before scheduling this work, I propose waiting to stand-up the Jupyterhub cluster we plan to host in our AWS account to give remote curation access to curators. This work may alleviate the pain points that led to this request such that its not as pressing to implement this feature.

This solution is an evolution of the proposed solution in #145, which is focused on uns-only updates (which is a simpler problem we already have infrastructure to accommodate)

Estimate: 5-6 weeks x 2 engineers

- Create endpoint `PATCH /v1/collections/{collection_id}/datasets` for submitting uns + obs dataset updates across a revision
- Propose a request schema capturing common patterns for scripting dataset updates (i.e. `{"update":{"cell_ontology_term_id": "CL:0000001", "donor_id": 1}}` to capture 'update CL to CL:0000001 if donor_id is 1')
- Input validation in the endpoint to determine if its a valid update action
-  trigger batch job that will parse request schema and perform the actions on datasets in the revision if conditions are met (or on all datasets in the revision if no conditions to check)
- Create a new batch job similar to `dataset_metadata_update.py` that iterates across datasets in a revision, parses the request schema for actions, and creates new dataset versions + applies applicable actions to the relevant dataset H5ADs (while updating dataset statuses accordingly). Then, apply those updates to the rds and cxg artifacts as well without going through the full conversion process.
       - NOTE: unlike  `dataset_metadata_update.py`, this batch job WILL require re-triggering the validation step if there are updates to the obs
       - To counter redundant work, Create an optional flag in the cellxgene-schema CLI to skip validating the X / raw.X matrix. Validating with this option will cover any potential new validation issues and avoid the most time / memory expensive operation.

**Comment by metakuni** [comment]
For future reference, this doc discusses the Jupyterhub cluster being created for curators:
* [Curation infrastructure for Lattice](https://docs.google.com/document/d/1ntfwJJ2LbtpHZodM2Rxe2mHvwqgjzAklgw7WqdmwK6A/edit#heading=h.oupicc5y5fgr)
* [Lattice curation infrastructure - design](https://docs.google.com/document/d/1Soh_Cbid1YaEgm6hm0R8Y2B0eX2SZTPCi68DOIXOo2E/edit#heading=h.a6xages0ico6)
* Slack: [#proj-sci-stanford-cherry-lab-support](https://czi.enterprise.slack.com/archives/C06TG95FJ2H)
