### ISSUE TITLE
Validate config file before deploying

### ISSUE THREAD

**Issue by MDunitz** [chanzuckerberg/single-cell#63]
## Need
- as a developer I want to save time and avoid deploying the cellxgene app with a faulty configuration requiring a redeploy

## Approach
- before deploying cellxgene validate the default config and any custom config settings

**Comment by bmccandless** [comment]
Yes, that's a great idea.

Depending on how we would do this, we might need to (or want to), add a section in the config file about the secrets manager, and the keys -> config parameters that it contains.   Currently the secrets manager handling is only in the "server/eb/app.py" part, and kind of ad hoc.   I think if we integrated it into the config file, then it's simpler, more flexible, and it would make it easier to validate the config before deploying.
