### ISSUE TITLE
[Delivery] As a Data Consumer, I want ontology modeling to be consistent across CELLxGENE experiences and to be accessible to me to reproduce in my own code.

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#639]
# [Tech Spec](https://docs.google.com/document/d/17Qv_9iJsztjcpu6CMpvbrjh8iJh2vwaSB13azFLBJO8/edit)

# Story

_As a Data Consumer, I want ontology modeling to be consistent across CELLxGENE experiences and to be accessible to me to reproduce in my own code._

**Comment by Bento007** [comment]
Epic is complete
