### ISSUE TITLE
User can explore and edit gene sets on desktop

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell#64]
User Story: As an eBio, I often want to explore the expression of groups of related genes instead of individual genes to better understand biological processes and identify cell types.

Requirements:

Loading a gene set
* Desktop users can load a csv containing gene sets from the command line
* Gene set conforms to gene set data format [#1860](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1860)
* Gene set names are strings that follow the same conventions as category names.
* Gene lists are non-redundant, non-mutually exclusive, and contain only features from var, see [#1609](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1069) for more info
* Users are warned in the UI when gene(s) do not import (are not included in the dataset)

Interacting with a gene set
* By default, gene sets are collapsed in the RSB and show a histogram of the mean expression
* The order genes are shown in in the UI reflects the order in the input file
* Users can color cells by average expression of a gene set
* Users can plot a gene set by x or y.
* Users can brush over the gene set to select a range of expression values
* Users can expand a gene set to see the individual genes
* On an expansion of an individual gene, a user sees a large histogram with axes, and brush to select range

Notes:
* For this epic, the "Autosuggest genes", "Bulk add genes" and "Add Gene" functionality will remain at the top of the RSB. Individual genes added will precede gene sets in the RSB

**Comment by signechambers1** [comment]
@colinmegill can you add instructions for the gene sets prototype to this epic? And links to figma as applicable. This will help dev know what the designs are and @ambrosejcarr demo as necessary.

**Comment by ambrosejcarr** [comment]
Instructions on use of gene sets prototype: 

```
git checkout colinmegill/geneset-prototype
make start-server CXG_OPTIONS="--experimental-annotations-ontology --experimental-enable-reembedding --debug --genesets-file ./data/krasnow-genesets.csv" DATASET=./data/krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.h5ad
make start-frontend
```

**Comment by signechambers1** [comment]
Closing in favor of https://app.zenhub.com/workspaces/cellxgene-explorer-600f112266e8830017f47e12/issues/chanzuckerberg/cellxgene/2041
