### ISSUE TITLE
[Discovery] Curators want to be notified when the DOI metadata for a collection is updated or corrected on Crossref

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#642]
# Context

See [**single-cell-discover-ux**](https://czi-sci.slack.com/archives/C02CF7MQPGV/p1698170413090949).

Motivated by:

1. Crossref corrected **primary author** metadata for a DOI that was previously retrieved when the Collection DOI was first submitted, so the CELLxGENE short citation was incorrect. @jahilton was forced to remove and re-add the DOI to retrieve the correct metadata and re-create the short citation. 

1. @jychien writes:

> Kuni and I had a chat about something that Jason and I had come across a number of times recently. People would contribute data pre-publication. And then many months later, their paper would actually publish (whether preprint or actual publication) and the CELLxGENE link is in the paper, but they would not contact us to make the Collection public.

---

There's already related work planned in [Increase the velocity of dataset schema evolution and dataset migration
](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/365)scoped to **Automate preprint DOI to published DOI updates**.

This scope should be extended in the future to check for updates and corrections.

---

It appears that CELLxGENE could cache `deposited` to compare against subsequent response queries:

`
"deposited":{"date-parts":[[2023,1,4]],"date-time":"2023-01-04T01:16:31Z","timestamp":1672794991000}
`

From [Crossref Metadata API JSON Format](https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md#crossref-metadata-api-json-format):

| Field | Type | Required | Description |
|-------|------|----------|-------------|
| deposited | [Date](#date) | Yes | Date on which the work metadata was most recently updated |
| indexed | [Date](#date) | Yes | Date on which the work metadata was most recently indexed. <br>Re-indexing does not imply a metadata change,<br>see `deposited` for the most recent metadata change date |

**Comment by metakuni** [comment]
Back link to chanzuckerberg/single-cell-data-portal#6322 for future reference

**Comment by nayib-jose-gloria** [comment]
Estimate: 1-2 weeks x 1 engineer + 1 reviewer

- If a collection version is a revision: Call Crossref API and check “deposited” date against the canonical collection's “revised_at” date (or the collection version's “published_at” date if "revised_at" is null) when publishing a collection version. If “deposited” is more recent, update collection metadata pulled from crossref (i.e. get published DOI if preprint and its been published, get updated author info). Can reuse existing functions for extracting collection metadata from Crossref.
- as a result, any DOI updates will regularly be picked up during migrations

**Comment by nayib-jose-gloria** [comment]
Implementation issue: https://github.com/chanzuckerberg/single-cell-data-portal/issues/6924

**Comment by metakuni** [comment]
Closing discovery as completed
