### ISSUE TITLE
Find and resolve all usages of/references to CL:0000003 and/or "native cell" across all repos

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell#647]
See [epic](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/611) description

**Comment by danieljhegeman** [comment]
References to "native cell" and CL:0000003 in single-cell-curation have been resolved already

**Comment by danieljhegeman** [comment]
Confirmed no instances of `0000003` for native cell that do not also include `CL:` prefix in data portal

**Comment by danieljhegeman** [comment]
Changes will need to be merged immediately _after_ migrations. FE filter compute script GHA should be run to regenerate ontology files for data portal from updated ontology version pins.

**Comment by danieljhegeman** [comment]
Data Portal changes are in `dan/647-replace-native-cell` (except for fixture updates, as addressed immediately above)

**Comment by danieljhegeman** [comment]
curation repo is clear

**Comment by danieljhegeman** [comment]
Explorer is clear

**Comment by danieljhegeman** [comment]
single-cell is clear

**Comment by danieljhegeman** [comment]
single-cell-analytics is clear

**Comment by danieljhegeman** [comment]
single-cell-ops-tools is clear

**Comment by danieljhegeman** [comment]
single-cell-infra is clear

**Comment by danieljhegeman** [comment]
cellxgene is clear

**Comment by danieljhegeman** [comment]
cellxgene-ontology-guide is clear

**Comment by danieljhegeman** [comment]
single-cell-annotation is clear

**Comment by danieljhegeman** [comment]
It looks like references to `CL:0000003` occurring in cellxgene-census all fall into the category of notebook _outputs_, meaning that once the ontology updates are pushed to prod, the notebooks can be rerun and the resulting output committed. This is also recapitulated in the html docs pages for Census, specifically [this one](https://github.com/chanzuckerberg/cellxgene-census/blob/0749eb2feba596695f6da5545e00bb098deab189/api/r/cellxgene.census/docs/articles/comp_bio_summarize_axis_query.html) and [this one](https://github.com/chanzuckerberg/cellxgene-census/blob/0749eb2feba596695f6da5545e00bb098deab189/api/r/cellxgene.census/docs/articles/census_axis_query.html).

**Comment by brianraymor** [comment]
I also see "native cell" referenced on a block list - [https://github.com/chanzuckerberg/cellxgene-census/blob/aaccb5b472a7f83a472986b098[…]3c12eeed/tools/models/geneformer/finetune-geneformer.config.yml](https://github.com/chanzuckerberg/cellxgene-census/blob/aaccb5b472a7f83a472986b098bf43173c12eeed/tools/models/geneformer/finetune-geneformer.config.yml#L5)

@danieljhegeman It would be good to review your findings with @pablo-gar and @bkmartinjr. We've recently discovered some subtle census issues with schema 4.0.0 changes.

**Comment by bkmartinjr** [comment]
@mlin - we need to update GeneFormer config as part of this.  I'll file a bug in Census tagging you.

**Comment by brianraymor** [comment]
Applications has a separate issue chanzuckerberg/single-cell-data-portal#6657 to address related changes.

Can this issue now be closed? CC: @danieljhegeman @metakuni

**Comment by danieljhegeman** [comment]
Since @atarashansky has ack'd [my PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/6666) and is assuming ownership of it, which I imagine he'll transfer to the issue you've linked above, then yes.

**Comment by danieljhegeman** [comment]
Closing per discussion above cc @atarashansky
