### ISSUE TITLE
Ensure that we can run a schema migration that is robust to deploys to that environment

### ISSUE THREAD

**Issue by joyceyan** [chanzuckerberg/single-cell#678]
Right now, if we're running the schema migration SFN in dev, and a deploy to dev occurs, we'll switch to using the newly deployed version of dev. This was a problem for the initial dev SFN run because the freshly deployed image of dev did not contain a reference to cellxgene-schema 5.0. This is not ideal because we have to either make sure deploys don't occur during the run of the SFN or re-run the SFN. We did the latter, which was ~okay because the second run picked up datasets that weren't migrated by the first run of the SFN.

Every step of the SFN pins the SFN job definition, [for example here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/.happy/terraform/modules/schema_migration/main.tf#L323). However, not the `DatasetMigration` step, which uses the [swap-enabled job definition](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/.happy/terraform/modules/schema_migration/main.tf#L381).

Some additional Slack context [here](https://czi-sci.slack.com/archives/C06AVGFV222/p1709157984364549).

**Comment by metakuni** [comment]
Added `P1` and `5.0` labels until we decide otherwise.

**Comment by joyceyan** [comment]
This PR by @nayib-jose-gloria should pin the DatasetMigration job to a specific job version: https://github.com/chanzuckerberg/single-cell-data-portal/pull/6755

However, this PR isn't sufficient to pin the job definition for the upload SFN that is spun off for each dataset (see StepFunctionsStartExecution in the definition linked, its still not pinned to a version).

**Comment by joyceyan** [comment]
Another option, suggested by @nayib-jose-gloria could be to update `Dockerfile.processing` to install the pinned github link to cellxgene-schema if HAPPY_BRANCH = dev

**Comment by joyceyan** [comment]
I'm going to close this out since we figured out how to properly freeze deploys to dev.
