### ISSUE TITLE
Delete empty uns dict keys

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell#684]
Many datasets are failing a schema validation requirement that uns not contain values that are empty (excludes `bool` and `NoneType` types).

**Comment by joyceyan** [comment]
A related issue we found is that this doesn't actually work if the value is `numpy.bool_`. Going to be putting up a fix to both the original validation code as well as the migrate script

**Comment by joyceyan** [comment]
This should now be closed with: https://github.com/chanzuckerberg/single-cell-curation/pull/803
