### ISSUE TITLE
Curators want to delete a dataset from a private collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#69]
**Story**

_Curators want to delete a dataset from a **private** collection._ 

The dataset and all of its _conversions_ (CXG, .rds, .loom, etc) MUST be deleted. The dataset will no longer appear in the list of datasets in the Collection. 

**Notes**

The original 2020 plan did not include deletion stories. 

---

**UX Design**

[Figma](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=526%3A349)

- Default state for delete button shows gray trash icon
- Hover state includes "Delete" label and turns red

---

**Dev Design**

1. FE calls delete endpoint 
2. BE marks the dataset as "tombstoned" in the the database in a single transaction (to support future dataset withdrawn scenarios). Issue delete commands to all S3 assets. Filter out "tombstoned" datasets in other API(s). 
3. BE returns 202 to FE (and will always return 202 for the same resource for duplicate calls)

**Comment by brianraymor** [comment]
@tihuan - This is pending the corresponding *FE* issue that is dependent on the @pdugan20 UX flow.

**Comment by pdugan20** [comment]
Yup! We have design proposals for taking a delete action, but they haven't been finalized yet.
