### ISSUE TITLE
Curators want to delete a private collection

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell#70]
**Story**

_Curators want to delete a **private** collection._ 

All the datasets in the private collection and their _conversions_ (CXG, .rds, .loom, etc) MUST be deleted. The collection will no longer appear in _My Collections_.

**Notes**

The 2020 plan does not include deletion stories. 

---

**UX Design**

[Figma](https://www.figma.com/file/g0L0CfVzRc8r6HQa4NH1wJ/Publisher-Collection?node-id=102%3A2384)

---

**Dev Design**

1. FE calls delete endpoint
2. BE marks the collection and its datasets as "tombstoned" in the the database in a single transaction (to support future dataset withdrawn scenarios). Issue delete commands to all S3 assets. Filter out "tombstoned" collections in other API(s).
3. BE returns 202 to FE (and will always return 202 for the same resource for duplicate calls)

**Comment by brianraymor** [comment]
@tihuan - This is pending the corresponding *FE* issue that is dependent on the @pdugan20 UX flow.

**Comment by pdugan20** [comment]
We'll have a similar approach to what we're doing for dataset deletion, likely an overflow menu with a delete option:
<img width="383" alt="Screen Shot 2020-10-06 at 6 49 14 PM" src="https://user-images.githubusercontent.com/1837100/95268099-a8cf9580-0804-11eb-8ed7-64d70c5ec30d.png">
