### ISSUE TITLE
Measure hosted cellxgene feature usage

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#9]
For the hosted cellxgene application
Note: This data will only reflects usage for users using cellxgene online, not usage locally or in their own hosted environment.

_Measure how many times key features are used per visit._
_Measure the probability that two key features are used in sequence_

**Business Justification**

This data will help us tailor UX research to understand if:
* features are difficult to use, or 
* features don't provide value to users, or
* features are used in particular flows or contexts, but not others.

Through measuring these metrics and UX research, we can make the following decisions:
* If a feature is difficult to use, we will consider adding in a tutorial or redesigning the feature.
* If a feature is not valuable, we will consider removing the feature to free up space for a more valuable feature.
* If features are used within a certain context but not others, we can incorporate this information into tutorials or future designs.

These analytics can also be useful to track any unexpected behavior changes a new feature launch may cause.

Note: We will defer major product decisions until the majority of our users move to hosted cellxgene and we are accurately capturing use patterns for most of our users.

**List of "key features"**

Left sidebar:
* painting by a category on left side bar
* selecting cells by unselecting some values within a category
* opening a category on left side bar
* creating a new category on left side bar

Top bar: 
* lassoing a selection of cells
* saving a selection of cells to a DE category
* saving a selection of cells to a category and assigning a label
* calculating differential expression between two categories
* subsetting to a selection of cells from a lasso selection
* returning to the full dataset
* selecting the zoom tool
* show labels on graph
* use the clip tool
* undo an action
* redo an action
* use the help menu, or any sub-menu item. 

Right sidebar: 
* Add a gene
* Bulk add genes
* create an xy plot
* color the scatterplot by a quantitative variable (e.g. gene expression)
* select a range of cells using the range selector

**Comment by MDunitz** [comment]
Have we talked to Trust about this? It seems like per visit and order of actions is getting pretty far into user tracking?

**Comment by brianraymor** [comment]
I raised with *Trust* on August 27 and pinged again this morning.

**Comment by brianraymor** [comment]
Per September 1 Refinement, @signechambers1 to follow up with @ambrosejcarr on the relative priority of this issue.

**Comment by signechambers1** [comment]
Trust approved the increased instrumentation on 9/15, from Shawn "Our current cellxgene policy covers this (see section 2.2) but I’ve made a note to spell this out even more since we are updating the policies for Data Portal anyways."

**Comment by brianraymor** [comment]
Per PM triage, closing. Ambrose will open a new issue to track specific actions.
